import { canonicalDigest } from "../../scripts/validate-rtcc-preview-complete-route-profile-v3.mjs";

const hash = (value: string) => canonicalDigest(value);
const owner = { exportName: "Root", sourcePath: "/source/root.tsx" };
const target = { exportName: "default", sourcePath: "/source/group.tsx" };

export function validFixture(mode: "route-root" | "page-root" | "multi-mount" = "route-root") {
  const routeId = "synthetic-route-17";
  const parameters = { groupId: "42" };
  const replayPolicyDigest = hash("replay-policy");
  const planPolicyDigest = hash("plan-policy");
  const root = { basePattern: "/", ...owner };
  const ownerChain = mode === "multi-mount" ? [root, { basePattern: "/workspace", exportName: "Workspace", sourcePath: "/source/workspace.tsx" }, { basePattern: "/workspace/groups", exportName: "Groups", sourcePath: "/source/groups.tsx" }] : [root];
  const selection = mode === "multi-mount" ? [{ componentName: "Root", pattern: "/*" }, { componentName: "Workspace", pattern: "/workspace/*" }, { componentName: "Groups", pattern: "/workspace/groups/*" }, { componentName: "Group", pattern: "/groups/:groupId(\\d+)" }] : [{ componentName: "Root", pattern: "/*" }, { componentName: "Group", pattern: "/groups/:groupId(\\d+)" }];
  const replay = { branchId: routeId, componentName: "Group", executionRoot: root, exportName: "default", owner, ownerChain, parameters, pathname: "/groups/42", pattern: "/groups/:groupId(\\d+)", policyDigest: replayPolicyDigest, routeSelectionResolution: "exact", runtimeTarget: target, selection, sourcePath: "/source/group.tsx", version: 1 };
  const planningContext = { compilerPolicyDigest: hash("compiler"), preparationPolicyDigest: hash("prepare"), requestDigest: hash("request"), resolutionConfinementDigest: hash("confinement"), resolverDigest: hash("resolver"), sourceSnapshotDigest: hash("snapshot") };
  const rootRole = { ...owner, surfaceId: "surface:root" };
  const targetRole = { ...target, surfaceId: "surface:target" };
  const routeMounts = mode === "multi-mount" ? [{ basePath: "/", childSurfaceId: "surface:workspace", contextPattern: "/*", hasWildcardFallback: true, parentSurfaceId: "surface:root", pattern: "/groups/:groupId(\\d+)" }, { basePath: "/workspace", childSurfaceId: "surface:groups", contextPattern: "/workspace/*", hasWildcardFallback: false, parentSurfaceId: "surface:workspace", pattern: "/groups/:groupId(\\d+)" }, { basePath: "/workspace/groups", childSurfaceId: "surface:target", contextPattern: "/workspace/groups/*", hasWildcardFallback: true, parentSurfaceId: "surface:groups", pattern: "/groups/:groupId(\\d+)" }] : [{ basePath: "/", childSurfaceId: "surface:target", contextPattern: "/*", hasWildcardFallback: true, parentSurfaceId: "surface:root", pattern: "/groups/:groupId(\\d+)" }];
  const recipe = { kind: "react-router-v6", mounts: mode === "page-root" ? [] : routeMounts, params: parameters, pathname: "/groups/42", pattern: "/groups/:groupId(\\d+)", rootOwnsRouter: false, routerModuleSpecifier: "react-router-dom", searchParams: {} };
  const executionRoot = mode === "page-root" ? targetRole : rootRole;
  const planOwnerChain = mode === "page-root" ? [{ basePattern: "/", ...target }] : ownerChain;
  const executionPlan: any = { browserCandidateId: "browser:synthetic-route-17", executionCandidateId: "execution:synthetic-route-17", executionIdentity: hash("execution"), executionRoot, frontierIdentity: hash("frontier"), ownerChain: planOwnerChain, pageCandidateId: "browser:synthetic-route-17", planningContext, planningContextDigest: canonicalDigest(planningContext), policyDigest: planPolicyDigest, recipe, rootRoleContract: { ...executionRoot, preparedSourceDigest: hash("root") }, routeId, runtimeTarget: targetRole, selectedBranch: { componentName: "Group", exportName: "default", id: routeId, pathname: "/groups/42", pattern: "/groups/:groupId(\\d+)", sourcePath: "/source/group.tsx" }, selection, targetRoleContract: { ...targetRole, preparedSourceDigest: hash("target") }, version: 2, digest: "" };
  executionPlan.digest = canonicalDigest(Object.fromEntries(Object.entries(executionPlan).filter(([key]) => key !== "digest")));
  const runnable = { id: routeId, componentName: "Group", exportName: "default", owner, parameters, pathname: "/groups/42", pattern: "/groups/:groupId(\\d+)", selection, sourcePath: "/source/group.tsx", disposition: "runnable", replay, executionPlan };
  const diagnostic = { diagnosticsVersion: 1, bundleMeasuredMicros: 1, frontierCount: 1, rawSourceReadCount: 2, rawSourceReadMicros: 1, inventoryReadRequestCount: 2, inventoryReadPathCacheHitCount: 0, sliceRequestCount: 3, sliceComputationCount: 2, sliceHitCount: 1, sliceLookupMicros: 1, inventoryRequestCount: 4, inventoryComputationCount: 3, inventoryHitCount: 1, inventoryLookupMicros: 1, queueIterationCount: 5, queuePeakLength: 3, queueSortCount: 5, queueSortMicros: 1, edgeVisitCount: 0, optionalClosureProbeCount: 0, optionalClosureMicros: 0, resolveModuleCount: 0, resolveModuleMicros: 0, authoredPathCheckCount: 0, authoredPathCheckMicros: 0, frontierFinalizeMicros: 0, frontierIdentityMicros: 0, candidateSelectionSortCount: 0, candidateSelectionMicros: 0 };
  const resource = (sequence: number) => ({ cpuSystemMicros: sequence, cpuUserMicros: sequence, elapsedMs: sequence, heapUsedBytes: sequence, rssBytes: sequence, sequence, version: 4 });
  const event = (sequence: number, phase: string, transition = "complete") => ({ event: { phase, transition, ...resource(sequence) }, kind: "progress", schemaVersion: 1 });
  const enumeration = (sequence: number, transition: string, analysisPasses: number) => ({ event: { analysisPasses, discoveredBranches: analysisPasses, enumerationPrefixComputationCount: 0, enumerationPrefixEntryCount: 0, enumerationPrefixHitCount: 0, enumerationPrefixRequestCount: 0, phase: "enumerate-branches", queuedSelections: analysisPasses, transition, ...resource(sequence) }, kind: "progress", schemaVersion: 1 });
  const replayEvent = (sequence: number, transition: string, replayCompleted: number) => ({ event: { phase: "replay-branches", replayPrefixComputationCount: 0, replayPrefixEntryCount: 0, replayPrefixHitCount: 0, replayPrefixRequestCount: 0, replayCompleted, replayTotal: 3, transition, ...resource(sequence) }, kind: "progress", schemaVersion: 1 });
  const execution = (sequence: number, phase: string, transition: string, bundle = false) => ({ event: { executionPlanCompleted: phase === "execution-frontier-plan" && transition === "complete" ? 1 : 0, executionPlanTotal: 1, routeOrdinal: 1, ...(bundle ? { bundleDiagnostics: diagnostic } : {}), phase, transition, ...resource(sequence) }, kind: "progress", schemaVersion: 1 });
  const executionSteps: [string, string, boolean?][] = [["execution-shared-context", "start"], ["execution-shared-context", "complete"], ["execution-route-usage", "start"], ["execution-route-usage", "complete"], ["execution-frontier-style", "start"], ["execution-frontier-style", "complete"], ["execution-frontier-globals", "start"], ["execution-frontier-globals", "complete"], ["execution-frontier-plan", "start"], ["execution-frontier-candidates", "start"], ["execution-frontier-candidates", "complete"], ["execution-frontier-bundle", "start"], ["execution-frontier-bundle", "complete", true], ["execution-frontier-ownership", "start"], ["execution-frontier-ownership", "complete"], ["execution-frontier-target-contract", "start"], ["execution-frontier-target-contract", "complete"], ["execution-frontier-root-contract", "start"], ["execution-frontier-root-contract", "complete"], ["execution-frontier-artifact", "start"], ["execution-frontier-artifact", "complete"], ["execution-frontier-plan", "complete"]];
  const progress = [event(1, "prepare-source"), enumeration(2, "start", 0), enumeration(3, "checkpoint", 1), enumeration(4, "checkpoint", 2), enumeration(5, "complete", 2), replayEvent(6, "start", 0), replayEvent(7, "checkpoint", 1), replayEvent(8, "checkpoint", 2), replayEvent(9, "checkpoint", 3), replayEvent(10, "complete", 3), ...executionSteps.map(([phase, transition, bundle], index) => execution(index + 11, phase, transition, bundle)), event(33, "finalize-inventory")];
  const records = [{ confinementPolicyDigest: "c", dependencyViewDigest: "d", isolationPolicyDigest: "i", isolationPolicyVersion: 3, kind: "header", maximumEvents: 20, noRetry: true, probeCapMs: 1, productionAggregate: "p", schemaVersion: 1, sourceManifestDigest: "s", telemetryPolicyDigest: "t", telemetryPolicyVersion: 4 }, ...progress, { cleanupConfirmed: true, eventCount: progress.length, finalSequence: progress.length, kind: "terminal", lastCounters: {}, lastPhase: "finalize-inventory", noRetry: true, schemaVersion: 1, inventory: { analysisPasses: 2, complete: true, counts: { duplicate: 0, runnable: 1, total: 1, unresolved: 0 }, dependencyPaths: ["/a", "/b"], entries: [runnable], limits: { maximumAnalysisPasses: 4096, maximumBranches: 8192, maximumDepth: 64 }, owner, predecessorVersion: 3, replayPasses: 3, replayPolicy: { digest: replayPolicyDigest, predecessorVersion: 3, version: 4 }, truncated: false, version: 4 }, status: "completed" }];
  return JSON.parse(JSON.stringify(records));
}

export const validRouteRootFixture = () => validFixture("route-root");
export const validPageRootFixture = () => validFixture("page-root");
export const validMultiMountFixture = () => validFixture("multi-mount");
