/**
 * Recovers unresolved tsconfig-alias imports whose source tree is explicitly documented as
 * generated and absent from the current checkout. The adapter is deliberately separate from
 * generated data-contract recovery: UI exports must remain valid React components so the authored
 * page can retain its layout while clearly marking substituted host nodes.
 */
import { createHash } from 'node:crypto';
import { readFileSync, statSync } from 'node:fs';
import path from 'node:path';
import type { OnLoadArgs, OnLoadResult, OnResolveArgs, OnResolveResult, Plugin } from 'esbuild';
import ts from 'typescript';
import {
  canonicalizeExistingPath,
  canonicalizePathThroughExistingAncestor,
} from '../../shared/pathIdentity';
import { createPreviewGeneratedUiSemanticStyleRuntimeSource } from './previewGeneratedUiSemanticStyles';
import { PREVIEW_RESOLVE_GUARD } from './previewPluginProtocol';
import type { PreviewStaticModuleResolver } from './previewStaticModuleResolver';
import { resolvePreviewYarnVirtualPath } from './previewYarnVirtualPath';

const GENERATED_UI_NAMESPACE = 'react-preview-generated-ui-fallback';
const MAXIMUM_MARKER_BYTES = 32 * 1024;
const MAXIMUM_MARKER_ANCESTORS = 5;
const MARKER_FILE_NAMES = ['README.md', 'README', 'GENERATED.md', '.gitignore'] as const;
const GENERATED_LANGUAGE_PATTERN = /\b(?:auto[- ]?generated|autogenerated|code[- ]?generated)\b/iu;
const GENERATED_CORROBORATION_PATTERN =
  /\b(?:build process|do not edit|generate(?:d|s| them)?|generation|gitignored|regenerat\w*)\b/iu;

/** Immutable compiler services used by generated UI recovery. */
export interface PreviewGeneratedUiFallbackOptions {
  /** Reads an editor snapshot when available; disk source is the bounded fallback. */
  readonly readSource?: (sourcePath: string) => string | undefined;
  /** Records the nearest existing generated root so its later creation triggers hot reload. */
  readonly registerWatchDirectory?: (directoryPath: string) => void;
  /** Resolves only explicit tsconfig path mappings and may return a not-yet-existing path. */
  readonly staticModuleResolver: Pick<
    PreviewStaticModuleResolver,
    'resolve' | 'resolveMissingPathAliasCandidate'
  >;
  /** Trusted workspace containing the importer, alias candidate, and generation marker. */
  readonly workspaceRoot: string;
}

/** Private metadata transported from the resolver to the generated UI loader. */
interface PreviewGeneratedUiFallbackData {
  /** Lexical missing source path selected by the importing file's nearest tsconfig. */
  readonly candidatePath: string;
  /** Names statically imported or accessed through this exact importing source. */
  readonly exportNames: readonly string[];
  /** Existing directory containing the strong generated-source marker. */
  readonly markerDirectory: string;
  /** Workspace-relative label shown in diagnostics and rendered placeholder attributes. */
  readonly moduleLabel: string;
}

/** Strong marker evidence retained only inside the extension host. */
interface PreviewGeneratedUiMarker {
  /** Existing directory watched for generated children. */
  readonly directoryPath: string;
  /** Exact bounded marker used to justify the fallback. */
  readonly markerPath: string;
}

/** Import/export demand discovered in one authored source for one exact module specifier. */
interface PreviewGeneratedUiExportRequest {
  /** Source-side export names required by named/default imports and explicit re-exports. */
  readonly exportNames: readonly string[];
  /** Whether an authored `export *` must forward names requested from the barrel itself. */
  readonly forwardsAllExports: boolean;
}

/** Mutable importer-wide request assembled during one AST traversal. */
interface PreviewGeneratedUiMutableExportRequest {
  /** De-duplicated source-side export names before stable sorting. */
  readonly exportNames: Set<string>;
  /** Set when this exact module specifier appears in an authored `export *`. */
  forwardsAllExports: boolean;
}

/**
 * Creates a fail-closed fallback for missing generated UI source reached through tsconfig aliases.
 *
 * Existing alias source is rejected by the static resolver before recovery. A replacement then
 * requires an explicit path mapping, canonical importer/candidate workspace confinement, an absent
 * source candidate, and a nearby marker that explicitly describes automatic generation.
 */
export function createPreviewGeneratedUiFallbackPlugin(
  options: PreviewGeneratedUiFallbackOptions,
): Plugin {
  const workspaceRoot = canonicalizeExistingPath(options.workspaceRoot);
  /** Marker discovery depends on a missing candidate's parent, not its individual leaf name. */
  const markerByCandidateDirectory = new Map<string, PreviewGeneratedUiMarker | null>();
  const requestedExportsBySource = new Map<string, Set<string>>();
  const warnedMarkerPaths = new Set<string>();
  return {
    name: 'react-preview-generated-ui-fallback',
    setup(build): void {
      /** Complete per-specifier demand from one importer-wide parse and traversal per rebuild. */
      const requestByImporter = new Map<string, Map<string, PreviewGeneratedUiExportRequest>>();
      build.onStart(() => {
        markerByCandidateDirectory.clear();
        requestByImporter.clear();
        requestedExportsBySource.clear();
      });

      /** Proves a missing generated alias lexically without recursively resolving every import. */
      function resolveGeneratedUi(arguments_: OnResolveArgs): OnResolveResult | undefined {
        if (
          arguments_.namespace !== 'file' ||
          (arguments_.pluginData as unknown) === PREVIEW_RESOLVE_GUARD ||
          arguments_.importer.length === 0
        ) {
          return undefined;
        }
        const importerPath = resolvePreviewYarnVirtualPath(arguments_.importer, workspaceRoot);
        if (
          importerPath === undefined ||
          !isPathInside(workspaceRoot, importerPath) ||
          isDependencyStorePath(importerPath, workspaceRoot)
        ) {
          return undefined;
        }
        const lexicalCandidatePath = options.staticModuleResolver.resolveMissingPathAliasCandidate(
          arguments_.path,
          importerPath,
        );
        if (lexicalCandidatePath === undefined) {
          if (!isRelativeModuleSpecifier(arguments_.path)) return undefined;
          propagateRequestedExportsToAuthoredModule(
            arguments_.path,
            importerPath,
            new Set(
              readRequestedExports(
                importerPath,
                arguments_.path,
                options.readSource,
                requestByImporter,
              ).exportNames,
            ),
            requestedExportsBySource,
            options.staticModuleResolver,
            workspaceRoot,
          );
          return undefined;
        }
        const request = readRequestedExports(
          importerPath,
          arguments_.path,
          options.readSource,
          requestByImporter,
        );
        const exportNames = new Set(request.exportNames);
        if (request.forwardsAllExports) {
          for (const exportName of requestedExportsBySource.get(sourceIdentity(importerPath)) ??
            []) {
            if (exportName !== 'default') exportNames.add(exportName);
          }
        }
        const candidatePath = canonicalizePathThroughExistingAncestor(lexicalCandidatePath);
        if (!isPathInside(workspaceRoot, candidatePath)) {
          return undefined;
        }
        const candidateDirectory = path.dirname(candidatePath);
        let marker = markerByCandidateDirectory.get(candidateDirectory);
        if (marker === undefined) {
          marker = findGeneratedUiMarker(candidatePath, workspaceRoot) ?? null;
          markerByCandidateDirectory.set(candidateDirectory, marker);
        }
        if (marker === null) return undefined;
        options.registerWatchDirectory?.(marker.directoryPath);
        const moduleLabel = formatWorkspacePath(candidatePath, workspaceRoot);
        return {
          namespace: GENERATED_UI_NAMESPACE,
          path: createImporterScopedModulePath(candidatePath, importerPath),
          pluginData: {
            candidatePath,
            exportNames: [...exportNames].sort(),
            markerDirectory: marker.directoryPath,
            moduleLabel,
          } satisfies PreviewGeneratedUiFallbackData,
          sideEffects: false,
        };
      }

      /** Emits one callable CommonJS proxy supporting arbitrary component and utility exports. */
      function loadGeneratedUi(arguments_: OnLoadArgs): OnLoadResult {
        const fallbackData = readFallbackData(arguments_.pluginData);
        if (fallbackData === undefined) {
          return { errors: [{ text: 'React Preview lost generated UI fallback metadata.' }] };
        }
        const markerPath = canonicalizeExistingPath(fallbackData.markerDirectory);
        const shouldWarn = !warnedMarkerPaths.has(markerPath);
        warnedMarkerPaths.add(markerPath);
        return {
          contents: createGeneratedUiModuleSource(
            fallbackData.moduleLabel,
            fallbackData.exportNames,
          ),
          loader: 'js',
          resolveDir: fallbackData.markerDirectory,
          warnings: shouldWarn
            ? [{ text: createGeneratedUiFallbackWarning(fallbackData.moduleLabel) }]
            : [],
          watchDirs: [fallbackData.markerDirectory],
        };
      }

      /** Re-enters ordinary file resolution for React imported by the private fallback namespace. */
      async function resolveGeneratedUiReact(arguments_: OnResolveArgs): Promise<OnResolveResult> {
        const resolveDirectory = arguments_.resolveDir || workspaceRoot;
        return await build.resolve(arguments_.path, {
          importer: path.join(resolveDirectory, '__react_preview_generated_ui__.js'),
          kind: arguments_.kind,
          namespace: 'file',
          pluginData: PREVIEW_RESOLVE_GUARD,
          resolveDir: resolveDirectory,
          with: arguments_.with,
        });
      }

      build.onResolve({ filter: /.*/ }, resolveGeneratedUi);
      build.onResolve(
        { filter: /^react$/, namespace: GENERATED_UI_NAMESPACE },
        resolveGeneratedUiReact,
      );
      build.onLoad({ filter: /.*/, namespace: GENERATED_UI_NAMESPACE }, loadGeneratedUi);
    },
  };
}

/**
 * Finds a nearby existing directory whose bounded marker explicitly documents generated output.
 * The ancestor limit prevents a generic monorepo README from authorizing unrelated missing aliases.
 */
function findGeneratedUiMarker(
  candidatePath: string,
  workspaceRoot: string,
): PreviewGeneratedUiMarker | undefined {
  let directoryPath = path.dirname(candidatePath);
  for (let depth = 0; depth <= MAXIMUM_MARKER_ANCESTORS; depth += 1) {
    if (!isPathInside(workspaceRoot, directoryPath)) return undefined;
    if (isDirectory(directoryPath)) {
      for (const markerName of MARKER_FILE_NAMES) {
        const markerPath = path.join(directoryPath, markerName);
        const markerText = readBoundedMarker(markerPath);
        if (markerText !== undefined && provesGeneratedSource(markerText, markerName)) {
          return { directoryPath, markerPath };
        }
      }
    }
    if (directoryPath === workspaceRoot) break;
    directoryPath = path.dirname(directoryPath);
  }
  return undefined;
}

/** Reads only small marker files so an authored README cannot consume unbounded build memory. */
function readBoundedMarker(markerPath: string): string | undefined {
  try {
    const markerSize = statSync(markerPath).size;
    if (markerSize <= 0 || markerSize > MAXIMUM_MARKER_BYTES) return undefined;
    return readFileSync(markerPath, 'utf8');
  } catch {
    return undefined;
  }
}

/** Requires explicit automatic-generation language plus an independent recovery/build signal. */
function provesGeneratedSource(markerText: string, markerName: string): boolean {
  if (markerName === '.gitignore') {
    return GENERATED_LANGUAGE_PATTERN.test(markerText) && /(?:^|\n)\s*[^#!\n]+/u.test(markerText);
  }
  return (
    GENERATED_LANGUAGE_PATTERN.test(markerText) && GENERATED_CORROBORATION_PATTERN.test(markerText)
  );
}

/**
 * Produces renderable CommonJS exports without assuming the unavailable design system's API.
 * PascalCase properties become lightweight host components; hooks and styling helpers receive
 * stable neutral values. Compound properties such as `Card.Header` remain callable components.
 */
function createGeneratedUiModuleSource(
  moduleLabel: string,
  exportNames: readonly string[],
): string {
  return [
    '/** Render-only React placeholders for an unavailable generated project UI module. */',
    "const React = require('react');",
    `const moduleLabel = ${JSON.stringify(moduleLabel)};`,
    'const exportCache = new Map();',
    'const maximumCompoundDepth = 6;',
    "const blockedReactStatics = new Set(['attrs', 'childContextTypes', 'compare', 'componentStyle', 'contextType', 'contextTypes', 'defaultProps', 'foldedComponentIds', 'getDefaultProps', 'getDerivedStateFromError', 'getDerivedStateFromProps', 'getSnapshotBeforeUpdate', 'mixins', 'propTypes', 'render', 'shouldForwardProp', 'styledComponentId', 'target', 'type', 'WrappedComponent']);",
    "const nativeEventNames = new Set(['onBlur', 'onChange', 'onClick', 'onFocus', 'onInput', 'onKeyDown', 'onKeyUp', 'onMouseDown', 'onMouseUp', 'onPointerDown', 'onPointerUp', 'onSubmit']);",
    "const overlayFamilies = ['AlertDialog', 'ContextMenu', 'Dialog', 'Drawer', 'DropdownMenu', 'HoverCard', 'Popover', 'Select', 'Sheet', 'Tooltip'];",
    'const overlayContext = React.createContext(undefined);',
    'const safeHostProps = (props) => {',
    '  const safe = {};',
    '  for (const [name, value] of Object.entries(props || {})) {',
    "    if (name === 'children' || name === 'asChild' || name === 'ref') continue;",
    '    if (',
    "      name === 'className' || name === 'style' || name === 'id' || name === 'title' ||",
    "      name === 'role' || name === 'tabIndex' || name === 'disabled' || name === 'href' ||",
    "      name === 'target' || name === 'rel' || name === 'type' || name === 'name' ||",
    "      name === 'placeholder' || name === 'value' || name === 'defaultValue' ||",
    "      name === 'checked' || name === 'defaultChecked' || name === 'min' || name === 'max' ||",
    "      name === 'step' || name === 'multiple' || name === 'accept' ||",
    "      name === 'alt' || name.startsWith('aria-') || name.startsWith('data-') ||",
    '      (nativeEventNames.has(name) && typeof value === "function")',
    '    ) safe[name] = value;',
    '  }',
    '  return safe;',
    '};',
    'const inferHostTag = (name) => {',
    "  if (/(?:Button|Trigger|Close)$/u.test(name)) return 'button';",
    "  if (/(?:TextArea|Textarea)$/u.test(name)) return 'textarea';",
    "  if (/(?:Input|Checkbox|Radio)$/u.test(name)) return 'input';",
    "  if (/Label$/u.test(name)) return 'label';",
    "  if (/(?:Image|AvatarImage)$/u.test(name)) return 'img';",
    "  if (/(?:Link|Anchor)$/u.test(name)) return 'a';",
    "  if (/Badge$/u.test(name)) return 'span';",
    "  if (/(?:Separator|Divider)$/u.test(name)) return 'hr';",
    "  if (/Table$/u.test(name)) return 'table';",
    "  if (/TableHeader$/u.test(name)) return 'thead';",
    "  if (/TableBody$/u.test(name)) return 'tbody';",
    "  if (/TableRow$/u.test(name)) return 'tr';",
    "  if (/TableHead$/u.test(name)) return 'th';",
    "  if (/TableCell$/u.test(name)) return 'td';",
    "  if (/List$/u.test(name)) return 'ul';",
    "  if (/ListItem$/u.test(name)) return 'li';",
    "  if (/Heading$/u.test(name)) return 'h2';",
    "  return 'div';",
    '};',
    "const readLeafName = (name) => name.split('.').at(-1) || name;",
    ...createPreviewGeneratedUiSemanticStyleRuntimeSource(),
    'const readOverlayRootFamily = (name) => {',
    '  const leafName = readLeafName(name);',
    '  return overlayFamilies.includes(leafName) ? leafName : undefined;',
    '};',
    'const readOverlayPart = (name) => {',
    '  for (const family of overlayFamilies) {',
    "    if (name.endsWith(family + 'Content') || name.endsWith(family + '.Content') ||",
    "        name.endsWith(family + 'Portal') || name.endsWith(family + '.Portal') ||",
    "        name.endsWith(family + 'Overlay') || name.endsWith(family + '.Overlay'))",
    "      return { family, kind: 'content' };",
    "    if (name.endsWith(family + 'Trigger') || name.endsWith(family + '.Trigger'))",
    "      return { family, kind: 'trigger' };",
    "    if (name.endsWith(family + 'Close') || name.endsWith(family + '.Close'))",
    "      return { family, kind: 'close' };",
    '  }',
    '  return undefined;',
    '};',
    'const createComponent = (name, compoundDepth = 0) => {',
    '  const component = function ReactPreviewGeneratedUiPlaceholder(props) {',
    '    const input = props || {};',
    '    const safe = safeHostProps(input);',
    '    const overlay = React.useContext(overlayContext);',
    '    const overlayPart = readOverlayPart(name);',
    '    const children = input.children;',
    '    const hostTag = inferHostTag(name);',
    '    const slottedChild = input.asChild && React.isValidElement(children) ? children : undefined;',
    '    const semanticStyle = mergeGeneratedUiSemanticStyle(',
    '      readGeneratedUiSemanticStyle(name, hostTag),',
    '      [slottedChild?.props?.style, input.style],',
    '    );',
    '    if (semanticStyle !== undefined) safe.style = semanticStyle;',
    "    safe['data-react-preview-generated-component'] = name;",
    "    safe['data-react-preview-generated-module'] = moduleLabel;",
    '    if (',
    "      overlayPart?.kind === 'content' &&",
    '      overlay?.family === overlayPart.family &&',
    '      overlay.open === false &&',
    '      input.forceMount !== true',
    '    ) {',
    '      safe.hidden = true;',
    "      safe['data-react-preview-generated-overlay'] = 'dormant';",
    "      return React.createElement('div', safe);",
    '    }',
    "    if ((overlayPart?.kind === 'trigger' || overlayPart?.kind === 'close') && overlay?.family === overlayPart.family) {",
    '      const authoredClick = safe.onClick;',
    '      safe.onClick = (event) => {',
    '        authoredClick?.(event);',
    "        if (event?.defaultPrevented !== true) overlay.onOpenChange?.(overlayPart.kind === 'trigger');",
    '      };',
    '    }',
    '    if (slottedChild !== undefined) {',
    '      return React.cloneElement(slottedChild, safe);',
    '    }',
    '    const hostChildren = /^(?:hr|img|input)$/u.test(hostTag) ? undefined : children;',
    '    const element = React.createElement(hostTag, safe, hostChildren);',
    '    const rootFamily = readOverlayRootFamily(name);',
    '    if (rootFamily === undefined) return element;',
    '    const open = typeof input.open === "boolean"',
    '      ? input.open',
    '      : typeof input.defaultOpen === "boolean" ? input.defaultOpen : false;',
    '    return React.createElement(overlayContext.Provider, {',
    '      value: {',
    '        family: rootFamily,',
    '        onOpenChange: typeof input.onOpenChange === "function" ? input.onOpenChange : undefined,',
    '        open,',
    '      },',
    '    }, element);',
    '  };',
    "  Object.defineProperty(component, 'displayName', { value: `PreviewGenerated(${name})` });",
    '  return new Proxy(component, {',
    '    get(target, property, receiver) {',
    "      if (property === 'then' || property === '$$typeof') return undefined;",
    '      if (blockedReactStatics.has(property)) return undefined;',
    '      if (Reflect.has(target, property)) return Reflect.get(target, property, receiver);',
    '      if (typeof property === \"symbol\") return undefined;',
    '      if (compoundDepth >= maximumCompoundDepth) return undefined;',
    '      return getExport(`${name}.${String(property)}`);',
    '    },',
    '  });',
    '};',
    'const createUtility = (name) => {',
    '  if (/^(?:use|create)[A-Z]/u.test(name)) {',
    '    const neutralValue = Object.freeze({});',
    '    return () => neutralValue;',
    '  }',
    "  if (/(?:Variants?|ClassNames?|Styles?)$/u.test(name)) return () => '';",
    '  return function ReactPreviewGeneratedUiNeutral() { return undefined; };',
    '};',
    'const getExport = (name) => {',
    '  if (exportCache.has(name)) return exportCache.get(name);',
    '  const leafName = readLeafName(name);',
    "  const compoundDepth = Math.max(0, name.split('.').length - 1);",
    '  const value = /^[A-Z]/u.test(leafName)',
    '    ? createComponent(name, compoundDepth)',
    '    : createUtility(leafName);',
    '  exportCache.set(name, value);',
    '  return value;',
    '};',
    "const moduleExports = createComponent('default');",
    `for (const exportName of ${JSON.stringify(exportNames)}) {`,
    "  if (exportName !== 'default' && !Reflect.has(moduleExports, exportName)) {",
    '    Object.defineProperty(moduleExports, exportName, {',
    '      configurable: true,',
    '      enumerable: true,',
    '      value: getExport(exportName),',
    '    });',
    '  }',
    '}',
    'module.exports = new Proxy(moduleExports, {',
    '  get(target, property, receiver) {',
    "    if (property === '__esModule') return false;",
    "    if (property === 'default') return target;",
    "    if (property === 'then' || property === '$$typeof') return undefined;",
    '    if (blockedReactStatics.has(property)) return undefined;',
    '    if (Reflect.has(target, property)) return Reflect.get(target, property, receiver);',
    '    if (typeof property === \"symbol\") return undefined;',
    '    return getExport(String(property));',
    '  },',
    '});',
  ].join('\n');
}

/** Validates private namespace metadata before reusing any filesystem path. */
function readFallbackData(value: unknown): PreviewGeneratedUiFallbackData | undefined {
  if (value === null || typeof value !== 'object') return undefined;
  const candidate = value as Partial<PreviewGeneratedUiFallbackData>;
  return typeof candidate.candidatePath === 'string' &&
    Array.isArray(candidate.exportNames) &&
    candidate.exportNames.every((exportName) => typeof exportName === 'string') &&
    typeof candidate.markerDirectory === 'string' &&
    typeof candidate.moduleLabel === 'string'
    ? (candidate as PreviewGeneratedUiFallbackData)
    : undefined;
}

/** Reads one request from an importer-wide analysis cached for the current esbuild rebuild. */
function readRequestedExports(
  importerPath: string,
  moduleSpecifier: string,
  readSource: PreviewGeneratedUiFallbackOptions['readSource'],
  requestByImporter: Map<string, Map<string, PreviewGeneratedUiExportRequest>>,
): PreviewGeneratedUiExportRequest {
  const importerIdentity = sourceIdentity(importerPath);
  let requestBySpecifier = requestByImporter.get(importerIdentity);
  if (requestBySpecifier === undefined) {
    requestBySpecifier = collectRequestedExportsBySpecifier(importerPath, readSource);
    requestByImporter.set(importerIdentity, requestBySpecifier);
  }
  return requestBySpecifier.get(moduleSpecifier) ?? { exportNames: [], forwardsAllExports: false };
}

/**
 * Parses and traverses one importer once to index every static import and re-export specifier.
 * Property accesses are collected by identifier during that same traversal, then associated with
 * namespace imports afterward so valid but unusually late import declarations remain supported.
 */
function collectRequestedExportsBySpecifier(
  importerPath: string,
  readSource: PreviewGeneratedUiFallbackOptions['readSource'],
): Map<string, PreviewGeneratedUiExportRequest> {
  let sourceFile: ts.SourceFile;
  try {
    const sourceText = readSource?.(importerPath) ?? readFileSync(importerPath, 'utf8');
    sourceFile = ts.createSourceFile(importerPath, sourceText, ts.ScriptTarget.Latest, false);
  } catch {
    return new Map();
  }
  const mutableRequestBySpecifier = new Map<string, PreviewGeneratedUiMutableExportRequest>();
  const namespaceSpecifiersByBinding = new Map<string, Set<string>>();
  const propertyNamesByBinding = new Map<string, Set<string>>();

  /** Creates one mutable bucket for all declarations targeting an exact authored specifier. */
  function getRequest(moduleSpecifier: string): PreviewGeneratedUiMutableExportRequest {
    const existingRequest = mutableRequestBySpecifier.get(moduleSpecifier);
    if (existingRequest !== undefined) return existingRequest;
    const request = { exportNames: new Set<string>(), forwardsAllExports: false };
    mutableRequestBySpecifier.set(moduleSpecifier, request);
    return request;
  }

  /** Adds one value to a set-valued index without allocating duplicate buckets. */
  function addIndexedValue(index: Map<string, Set<string>>, key: string, value: string): void {
    const values = index.get(key) ?? new Set<string>();
    values.add(value);
    index.set(key, values);
  }

  const visit = (node: ts.Node): void => {
    if (ts.isImportDeclaration(node) && ts.isStringLiteralLike(node.moduleSpecifier)) {
      const moduleSpecifier = node.moduleSpecifier.text;
      const request = getRequest(moduleSpecifier);
      if (node.importClause?.name !== undefined) request.exportNames.add('default');
      const bindings = node.importClause?.namedBindings;
      if (bindings !== undefined && ts.isNamedImports(bindings)) {
        for (const binding of bindings.elements) {
          request.exportNames.add(binding.propertyName?.text ?? binding.name.text);
        }
      } else if (bindings !== undefined && ts.isNamespaceImport(bindings)) {
        addIndexedValue(namespaceSpecifiersByBinding, bindings.name.text, moduleSpecifier);
      }
    }
    if (
      ts.isExportDeclaration(node) &&
      node.moduleSpecifier !== undefined &&
      ts.isStringLiteralLike(node.moduleSpecifier)
    ) {
      const request = getRequest(node.moduleSpecifier.text);
      if (node.exportClause === undefined) {
        request.forwardsAllExports = true;
      } else if (ts.isNamedExports(node.exportClause)) {
        for (const binding of node.exportClause.elements) {
          request.exportNames.add(binding.propertyName?.text ?? binding.name.text);
        }
      }
    }
    if (ts.isPropertyAccessExpression(node) && ts.isIdentifier(node.expression)) {
      addIndexedValue(propertyNamesByBinding, node.expression.text, node.name.text);
    }
    ts.forEachChild(node, visit);
  };
  visit(sourceFile);

  for (const [bindingName, moduleSpecifiers] of namespaceSpecifiersByBinding) {
    const propertyNames = propertyNamesByBinding.get(bindingName) ?? [];
    for (const moduleSpecifier of moduleSpecifiers) {
      const request = getRequest(moduleSpecifier);
      for (const propertyName of propertyNames) request.exportNames.add(propertyName);
    }
  }
  return new Map(
    [...mutableRequestBySpecifier].map(([moduleSpecifier, request]) => [
      moduleSpecifier,
      {
        exportNames: [...request.exportNames].sort(),
        forwardsAllExports: request.forwardsAllExports,
      },
    ]),
  );
}

/** Limits barrel-demand tracking to explicit relative authored edges. */
function isRelativeModuleSpecifier(moduleSpecifier: string): boolean {
  const cleanSpecifier = moduleSpecifier.split(/[?#]/u, 1)[0];
  return cleanSpecifier !== undefined && /^\.\.?\//u.test(cleanSpecifier);
}

/** Excludes package-manager stores whose large dependency graphs cannot contain project aliases. */
function isDependencyStorePath(sourcePath: string, workspaceRoot: string): boolean {
  const segments = path.relative(workspaceRoot, sourcePath).split(path.sep);
  return segments.includes('node_modules') || segments.includes('.yarn');
}

/**
 * Carries named demand across an existing relative barrel before esbuild loads its dependencies.
 * This avoids a workspace scan: a downstream `import { Button } from './barrel'` records `Button`
 * on that exact authored file, and its later `export *` can make the missing generated proxy expose
 * a statically enumerable property. Package imports are intentionally excluded from this fast path.
 */
function propagateRequestedExportsToAuthoredModule(
  moduleSpecifier: string,
  importerPath: string,
  exportNames: ReadonlySet<string>,
  requestedExportsBySource: Map<string, Set<string>>,
  staticModuleResolver: Pick<PreviewStaticModuleResolver, 'resolve'>,
  workspaceRoot: string,
): void {
  const cleanSpecifier = moduleSpecifier.split(/[?#]/u, 1)[0];
  if (exportNames.size === 0 || cleanSpecifier === undefined || !/^\.\.?\//u.test(cleanSpecifier)) {
    return;
  }
  const resolvedPath = staticModuleResolver.resolve(cleanSpecifier, importerPath);
  if (resolvedPath === undefined || !isPathInside(workspaceRoot, resolvedPath)) return;
  const targetNames =
    requestedExportsBySource.get(sourceIdentity(resolvedPath)) ?? new Set<string>();
  for (const exportName of exportNames) targetNames.add(exportName);
  requestedExportsBySource.set(sourceIdentity(resolvedPath), targetNames);
}

/** Uses one canonical key for disk, snapshot, and Yarn-linked authored source identities. */
function sourceIdentity(sourcePath: string): string {
  return canonicalizeExistingPath(sourcePath);
}

/** Creates a bounded stable virtual identity for one missing module/importer pair. */
function createImporterScopedModulePath(candidatePath: string, importerPath: string): string {
  const importerHash = createHash('sha256').update(importerPath).digest('hex').slice(0, 16);
  return `${candidatePath}#${importerHash}`;
}

/** Explains both the substitution and the project action that restores real design-system output. */
function createGeneratedUiFallbackWarning(moduleLabel: string): string {
  return `Generated project UI source "${moduleLabel}" is unavailable. React Preview supplied renderable structural placeholders; run the project's documented generation command to restore exact components and styles.`;
}

/** Formats one trusted path without exposing unrelated absolute host directories. */
function formatWorkspacePath(sourcePath: string, workspaceRoot: string): string {
  return (
    path.relative(workspaceRoot, sourcePath).replaceAll(path.sep, '/') || path.basename(sourcePath)
  );
}

/** Checks a candidate directory without throwing for absent or transient generated paths. */
function isDirectory(candidatePath: string): boolean {
  try {
    return statSync(candidatePath).isDirectory();
  } catch {
    return false;
  }
}

/** Checks workspace containment without accepting sibling-prefix lookalikes. */
function isPathInside(rootPath: string, candidatePath: string): boolean {
  const relativePath = path.relative(path.resolve(rootPath), path.resolve(candidatePath));
  return (
    relativePath.length === 0 ||
    (relativePath !== '..' &&
      !relativePath.startsWith(`..${path.sep}`) &&
      !path.isAbsolute(relativePath))
  );
}
