/**
 * Generates the browser-only `events` compatibility module used by preview bundles.
 *
 * Some browser-ready packages still inherit from Node's EventEmitter through their legacy entry
 * point. A generic callable proxy cannot satisfy those packages because they enumerate methods on
 * `EventEmitter.prototype`. This shim implements only in-memory listener bookkeeping and never
 * exposes extension-host Node capabilities to workspace code.
 */

/**
 * Creates a CommonJS EventEmitter implementation with enumerable prototype methods.
 *
 * Enumerable methods are intentional: PouchDB and similar legacy packages copy the prototype with
 * `Object.keys(EventEmitter.prototype)` before attaching static lifecycle events to a constructor.
 * The implementation stays deliberately small, synchronous, and browser-local.
 */
export function createPreviewNodeEventsRuntimeSource(): string {
  return [
    "'use strict';",
    'const listenersByEmitter = new WeakMap();',
    'function readListenerMap(emitter) {',
    '  let listeners = listenersByEmitter.get(emitter);',
    '  if (listeners === undefined) {',
    '    listeners = new Map();',
    '    listenersByEmitter.set(emitter, listeners);',
    '  }',
    '  return listeners;',
    '}',
    'function EventEmitter() {',
    '  if (!(this instanceof EventEmitter)) return new EventEmitter();',
    '  readListenerMap(this);',
    '}',
    'function addListener(eventName, listener) {',
    "  if (typeof listener !== 'function') return this;",
    '  const listeners = readListenerMap(this);',
    '  const current = listeners.get(eventName) ?? [];',
    '  current.push(listener);',
    '  listeners.set(eventName, current);',
    '  return this;',
    '}',
    'function prependListener(eventName, listener) {',
    "  if (typeof listener !== 'function') return this;",
    '  const listeners = readListenerMap(this);',
    '  const current = listeners.get(eventName) ?? [];',
    '  current.unshift(listener);',
    '  listeners.set(eventName, current);',
    '  return this;',
    '}',
    'function once(eventName, listener) {',
    "  if (typeof listener !== 'function') return this;",
    '  const emitter = this;',
    '  function onceListener(...arguments_) {',
    '    emitter.removeListener(eventName, onceListener);',
    '    return listener.apply(emitter, arguments_);',
    '  }',
    '  onceListener.listener = listener;',
    '  return this.addListener(eventName, onceListener);',
    '}',
    'function prependOnceListener(eventName, listener) {',
    "  if (typeof listener !== 'function') return this;",
    '  const emitter = this;',
    '  function onceListener(...arguments_) {',
    '    emitter.removeListener(eventName, onceListener);',
    '    return listener.apply(emitter, arguments_);',
    '  }',
    '  onceListener.listener = listener;',
    '  return this.prependListener(eventName, onceListener);',
    '}',
    'function removeListener(eventName, listener) {',
    '  const listeners = readListenerMap(this);',
    '  const current = listeners.get(eventName);',
    '  if (!Array.isArray(current)) return this;',
    '  const index = current.findIndex((candidate) =>',
    '    candidate === listener || candidate.listener === listener,',
    '  );',
    '  if (index >= 0) current.splice(index, 1);',
    '  if (current.length === 0) listeners.delete(eventName);',
    '  return this;',
    '}',
    'function removeAllListeners(eventName) {',
    '  const listeners = readListenerMap(this);',
    '  if (arguments.length === 0) listeners.clear();',
    '  else listeners.delete(eventName);',
    '  return this;',
    '}',
    'function emit(eventName, ...arguments_) {',
    '  const current = readListenerMap(this).get(eventName);',
    '  if (!Array.isArray(current) || current.length === 0) return false;',
    '  for (const listener of [...current]) listener.apply(this, arguments_);',
    '  return true;',
    '}',
    'function listeners(eventName) {',
    '  return (readListenerMap(this).get(eventName) ?? []).map(',
    '    (listener) => listener.listener ?? listener,',
    '  );',
    '}',
    'function rawListeners(eventName) {',
    '  return [...(readListenerMap(this).get(eventName) ?? [])];',
    '}',
    'function listenerCount(eventName) {',
    '  return (readListenerMap(this).get(eventName) ?? []).length;',
    '}',
    'function eventNames() {',
    '  return [...readListenerMap(this).keys()];',
    '}',
    'function setMaxListeners() { return this; }',
    'function getMaxListeners() { return 0; }',
    'const methods = {',
    '  addListener, emit, eventNames, getMaxListeners, listenerCount, listeners,',
    '  off: removeListener, on: addListener, once, prependListener, prependOnceListener,',
    '  rawListeners, removeAllListeners, removeListener, setMaxListeners,',
    '};',
    'for (const [name, method] of Object.entries(methods)) {',
    '  Object.defineProperty(EventEmitter.prototype, name, {',
    '    configurable: true, enumerable: true, value: method, writable: true,',
    '  });',
    '}',
    'EventEmitter.EventEmitter = EventEmitter;',
    'EventEmitter.defaultMaxListeners = 10;',
    'EventEmitter.listenerCount = (emitter, eventName) =>',
    "  typeof emitter?.listenerCount === 'function' ? emitter.listenerCount(eventName) : 0;",
    'EventEmitter.init = function init() { readListenerMap(this); };',
    'module.exports = EventEmitter;',
    'module.exports.EventEmitter = EventEmitter;',
    'module.exports.default = EventEmitter;',
  ].join('\n');
}
