/**
 * Generates a browser-only POSIX subset of Node's `path` module.
 *
 * Server-authored render helpers frequently normalize already-bundled registry metadata before a
 * component is selected. Those operations are pure string transforms and need no host filesystem
 * capability, but the generic callable builtin fallback returns `undefined` and erases paths that
 * later code legitimately splits or validates. This facade keeps those transforms deterministic
 * inside the webview while retaining `/` as the isolated preview root.
 */

/** Returns CommonJS source implementing the ordinary path operations used by render metadata. */
export function createPreviewNodePathRuntimeSource(): string {
  return [
    '/** Rejects non-string values with the same public contract as Node path helpers. */',
    'function assertPath(value) {',
    "  if (typeof value !== 'string') throw new TypeError('Path must be a string.');",
    '}',
    '/** Reads only the browser-local process facade and never a host working directory. */',
    'function readWorkingDirectory() {',
    '  try {',
    '    const value = globalThis.process?.cwd?.();',
    "    return typeof value === 'string' && value.startsWith('/') ? value : '/';",
    '  } catch {',
    "    return '/';",
    '  }',
    '}',
    '/** Collapses POSIX dot segments without consulting the filesystem. */',
    'function normalizeSegments(value, allowAboveRoot) {',
    '  const output = [];',
    "  for (const segment of value.split('/')) {",
    "    if (segment.length === 0 || segment === '.') continue;",
    "    if (segment === '..') {",
    "      if (output.length > 0 && output.at(-1) !== '..') output.pop();",
    "      else if (allowAboveRoot) output.push('..');",
    '      continue;',
    '    }',
    '    output.push(segment);',
    '  }',
    '  return output;',
    '}',
    'function normalize(value) {',
    '  assertPath(value);',
    "  if (value.length === 0) return '.';",
    "  const absolute = value.startsWith('/');",
    "  const trailing = value.endsWith('/');",
    "  const body = normalizeSegments(value, !absolute).join('/');",
    "  if (body.length === 0) return absolute ? '/' : '.';",
    "  return (absolute ? '/' : '') + body + (trailing ? '/' : '');",
    '}',
    'function resolve(...values) {',
    "  let joined = '';",
    '  let absolute = false;',
    '  for (let index = values.length - 1; index >= -1 && !absolute; index -= 1) {',
    '    const value = index >= 0 ? values[index] : readWorkingDirectory();',
    '    assertPath(value);',
    '    if (value.length === 0) continue;',
    "    joined = value + '/' + joined;",
    "    absolute = value.startsWith('/');",
    '  }',
    "  const body = normalizeSegments(joined, !absolute).join('/');",
    "  return (absolute ? '/' : '') + body || (absolute ? '/' : '.');",
    '}',
    'function join(...values) {',
    '  for (const value of values) assertPath(value);',
    "  const joined = values.filter((value) => value.length > 0).join('/');",
    "  return joined.length === 0 ? '.' : normalize(joined);",
    '}',
    'function isAbsolute(value) {',
    '  assertPath(value);',
    "  return value.startsWith('/');",
    '}',
    'function relative(from, to) {',
    '  assertPath(from);',
    '  assertPath(to);',
    '  const fromResolved = resolve(from);',
    '  const toResolved = resolve(to);',
    "  if (fromResolved === toResolved) return '';",
    "  const fromParts = fromResolved.split('/').filter(Boolean);",
    "  const toParts = toResolved.split('/').filter(Boolean);",
    '  let common = 0;',
    '  while (common < fromParts.length && common < toParts.length && fromParts[common] === toParts[common]) common += 1;',
    "  return [...Array.from({ length: fromParts.length - common }, () => '..'), ...toParts.slice(common)].join('/');",
    '}',
    'function dirname(value) {',
    '  assertPath(value);',
    "  if (value.length === 0) return '.';",
    '  let end = value.length - 1;',
    "  while (end > 0 && value[end] === '/') end -= 1;",
    "  const slash = value.lastIndexOf('/', end);",
    "  if (slash < 0) return '.';",
    "  if (slash === 0) return '/';",
    '  return value.slice(0, slash);',
    '}',
    'function basename(value, suffix) {',
    '  assertPath(value);',
    '  if (suffix !== undefined) assertPath(suffix);',
    '  let end = value.length - 1;',
    "  while (end >= 0 && value[end] === '/') end -= 1;",
    "  if (end < 0) return '';",
    "  const slash = value.lastIndexOf('/', end);",
    '  let result = value.slice(slash + 1, end + 1);',
    '  if (suffix && result.endsWith(suffix)) result = result.slice(0, -suffix.length);',
    '  return result;',
    '}',
    'function extname(value) {',
    '  const base = basename(value);',
    "  const dot = base.lastIndexOf('.');",
    "  return dot <= 0 ? '' : base.slice(dot);",
    '}',
    'function parse(value) {',
    '  assertPath(value);',
    "  const root = value.startsWith('/') ? '/' : '';",
    '  const dir = dirname(value);',
    '  const base = basename(value);',
    '  const ext = extname(base);',
    '  const name = ext.length === 0 ? base : base.slice(0, -ext.length);',
    "  return { root, dir: dir === '.' && root ? root : dir, base, ext, name };",
    '}',
    'function format(value) {',
    "  const directory = value?.dir || value?.root || '';",
    "  const base = value?.base || ((value?.name || '') + (value?.ext || ''));",
    "  return directory.length === 0 ? base : directory === '/' ? '/' + base : directory + '/' + base;",
    '}',
    'const facade = {',
    '  resolve, normalize, isAbsolute, join, relative, dirname, basename, extname, format, parse,',
    "  toNamespacedPath(value) { return value; }, sep: '/', delimiter: ':',",
    '};',
    'facade.posix = facade;',
    'facade.win32 = facade;',
    'module.exports = facade;',
    "console.warn('[React Preview] Node built-in path uses a browser-local POSIX string facade.');",
  ].join('\n');
}
