/**
 * Generates a browser-to-host health stream for preview compatibility decisions and error chains.
 * This layer is deliberately separate from blocker state: blocker traces explain user/Auto choices,
 * while health events explain the renderer mechanisms that may hide CSS, alter package resolution,
 * or produce a secondary fallback failure after the original application exception.
 */

/** Creates bounded browser source for health event correlation and live host delivery. */
export function createPreviewInspectorRuntimeHealthSource(): string {
  return String.raw`
const PREVIEW_INSPECTOR_HEALTH_RECORD_LIMIT = 256;
const PREVIEW_INSPECTOR_HEALTH_ERROR_ROOT_LIMIT = 64;
const PREVIEW_INSPECTOR_HEALTH_TEXT_LIMIT = 4_000;
const PREVIEW_INSPECTOR_HEALTH_ERROR_CHAIN_MS = 5_000;
const previewInspectorRuntimeHealthEvents = new Set([
  'graphql-interpolation-repaired',
  'page-context-selected',
  'render-attempt-started',
  'render-attempt-settled',
  'runtime-effect-isolated',
  'runtime-error-cascade',
  'runtime-error-fallback',
  'runtime-error-root',
  'styled-components-instance-warning',
  'theme-boundary-composed',
  'theme-token-repaired',
]);

/** Initializes ephemeral health state that survives Inspector refreshes but not webview disposal. */
function initializePreviewInspectorRuntimeHealthState() {
  if (!(previewInspectorSession.runtimeHealthFingerprints instanceof Map)) {
    previewInspectorSession.runtimeHealthFingerprints = new Map();
  }
  if (!(previewInspectorSession.runtimeHealthRootErrors instanceof Map)) {
    previewInspectorSession.runtimeHealthRootErrors = new Map();
  }
  if (!Number.isSafeInteger(previewInspectorSession.runtimeHealthSequence)) {
    previewInspectorSession.runtimeHealthSequence = 0;
  }
}

/** Copies renderer-owned diagnostic data into a bounded JSON-compatible value. */
function copyPreviewInspectorRuntimeHealthValue(
  value,
  depth = 0,
  state = { nodes: 0, seen: new WeakSet() },
) {
  state.nodes += 1;
  if (state.nodes > 384) return '[Node limit]';
  if (typeof value === 'string') return value.slice(0, PREVIEW_INSPECTOR_HEALTH_TEXT_LIMIT);
  if (value === null || typeof value === 'boolean') return value;
  if (typeof value === 'number') return Number.isFinite(value) ? value : String(value);
  if (value === undefined) return '[undefined]';
  if (typeof value === 'bigint') return String(value) + 'n';
  if (typeof value === 'symbol' || typeof value === 'function') return '[' + typeof value + ']';
  if (typeof value !== 'object') return '[' + typeof value + ']';
  if (state.seen.has(value)) return '[Circular]';
  if (depth >= 5) return '[Depth limit]';
  state.seen.add(value);
  let isArray = false;
  try { isArray = Array.isArray(value); } catch { return '[Uninspectable]'; }
  if (isArray) {
    return value.slice(0, 48).map((item) =>
      copyPreviewInspectorRuntimeHealthValue(item, depth + 1, state),
    );
  }
  let keys;
  try { keys = Object.keys(value).slice(0, 48); } catch { return '[Uninspectable]'; }
  const result = {};
  for (const key of keys) {
    if (blockedInspectorPropNames.has(key)) continue;
    let descriptor;
    try { descriptor = Object.getOwnPropertyDescriptor(value, key); } catch { descriptor = undefined; }
    if (descriptor === undefined || !('value' in descriptor)) continue;
    result[key] = copyPreviewInspectorRuntimeHealthValue(descriptor.value, depth + 1, state);
  }
  return result;
}

/** Returns source evidence generated by the compiler without accepting project object accessors. */
function readPreviewInspectorRuntimeHealthSource(detail) {
  const evidence = detail?.evidence;
  if (evidence === null || typeof evidence !== 'object') return undefined;
  const sourcePath = typeof evidence.sourcePath === 'string' ? evidence.sourcePath : '';
  if (!(sourcePath.startsWith('/') || /^[A-Za-z]:[\\/]/u.test(sourcePath))) return undefined;
  const source = { sourcePath: sourcePath.slice(0, 16_384) };
  if (Number.isSafeInteger(evidence.line) && evidence.line > 0) source.line = evidence.line;
  if (Number.isSafeInteger(evidence.column) && evidence.column > 0) source.column = evidence.column;
  return source;
}

/** Resolves severity from the compatibility action rather than trusting a project-supplied value. */
function readPreviewInspectorRuntimeHealthSeverity(event) {
  if (event.startsWith('runtime-error')) {
    return 'error';
  }
  return event === 'graphql-interpolation-repaired' ||
    event === 'runtime-effect-isolated' ||
    event === 'theme-token-repaired' ||
    event === 'styled-components-instance-warning'
    ? 'warn'
    : 'info';
}

/**
 * Distinguishes React compatibility/deprecation diagnostics from failures that prevented a commit.
 * React emits several non-fatal development warnings through console.error, so the transport level
 * alone cannot decide whether a warning starts a runtime failure chain.
 */
function isPreviewInspectorNonFatalReactDiagnostic(message) {
  return /(?:findDOMNode is deprecated|Each child in a list should have a unique|React does not recognize the|Invalid (?:DOM property|attribute name)|validateDOMNesting|Received .* for a non-boolean attribute|A component is changing an? (?:un)?controlled|AG Grid: error #272)/u.test(
    message,
  );
}

/** Emits one deduplicated health event and returns its revision-local identity. */
function recordPreviewInspectorRuntimeHealth(candidate = {}) {
  initializePreviewInspectorRuntimeHealthState();
  const event = typeof candidate.event === 'string' ? candidate.event : '';
  if (!previewInspectorRuntimeHealthEvents.has(event)) return undefined;
  const category = typeof candidate.category === 'string'
    ? candidate.category.slice(0, 80)
    : 'renderer';
  const detail = copyPreviewInspectorRuntimeHealthValue(candidate.detail ?? {});
  const parentEventId = typeof candidate.parentEventId === 'string'
    ? candidate.parentEventId.slice(0, 160)
    : undefined;
  const source = readPreviewInspectorRuntimeHealthSource(candidate.detail);
  let fingerprint;
  try {
    fingerprint = JSON.stringify([
      previewEntryRevision,
      category,
      event,
      parentEventId,
      detail,
      source,
    ]);
  } catch {
    fingerprint = String(previewEntryRevision) + ':' + category + ':' + event;
  }
  if (previewInspectorSession.runtimeHealthFingerprints.has(fingerprint)) return undefined;
  previewInspectorSession.runtimeHealthSequence += 1;
  const eventId = 'runtime-health-' + String(previewInspectorSession.runtimeHealthSequence);
  previewInspectorSession.runtimeHealthFingerprints.set(fingerprint, eventId);
  if (previewInspectorSession.runtimeHealthFingerprints.size > PREVIEW_INSPECTOR_HEALTH_RECORD_LIMIT) {
    previewInspectorSession.runtimeHealthFingerprints.delete(
      previewInspectorSession.runtimeHealthFingerprints.keys().next().value,
    );
  }
  try {
    previewInspectorPostHostMessage?.({
      event: {
        category,
        detail,
        event,
        eventId,
        ...(parentEventId === undefined ? {} : { parentEventId }),
        revision: previewEntryRevision,
        sequence: previewInspectorSession.runtimeHealthSequence,
        severity: readPreviewInspectorRuntimeHealthSeverity(event),
        ...(source === undefined ? {} : { source }),
        target: readPreviewInspectorBlockerTraceTarget(),
        timestamp: new Date().toISOString(),
      },
      type: 'react-preview-runtime-health',
    });
  } catch {
    /* Health delivery cannot participate in project rendering. */
  }
  return eventId;
}

/** Creates a stable error-chain key for the currently selected page candidate and export. */
function createPreviewInspectorRuntimeHealthErrorKey(entry) {
  return [
    previewEntryRevision,
    previewInspectorSession.selectedPageCandidateId ?? '',
    entry?.exportName ?? previewInspectorSession.selectedExportName ?? '',
  ].join(':');
}

/** Reports root, cascade, and error-fallback failures without claiming heuristic certainty. */
function recordPreviewInspectorRuntimeHealthError(entry) {
  const rawMessage = String(entry?.message ?? '[Runtime error]');
  const isStyledComponentsInstanceWarning =
    /several instances of ['"]styled-components['"]/u.test(rawMessage);
  if (entry?.level !== 'error' && !(entry?.level === 'warn' && isStyledComponentsInstanceWarning)) {
    return;
  }
  if (!isStyledComponentsInstanceWarning && isPreviewInspectorNonFatalReactDiagnostic(rawMessage)) {
    return;
  }
  initializePreviewInspectorRuntimeHealthState();
  const source = typeof entry.source === 'string' ? entry.source : 'runtime';
  if (!['console', 'preview-runtime', 'react-boundary', 'runtime-fallback', 'target-reachability'].includes(source)) return;
  const message = rawMessage.slice(0, PREVIEW_INSPECTOR_HEALTH_TEXT_LIMIT);
  const key = createPreviewInspectorRuntimeHealthErrorKey(entry);
  const now = Date.now();
  const previousRoot = previewInspectorSession.runtimeHealthRootErrors.get(key);
  const componentStack = typeof entry.componentStack === 'string' ? entry.componentStack : '';
  const hasFallbackEvidence = source === 'runtime-fallback' ||
    /(?:ErrorBoundary|ErrorStatus|Fallback|NotFoundStatus)/u.test(componentStack);
  const followsRoot = !isStyledComponentsInstanceWarning && previousRoot !== undefined &&
    now - previousRoot.timestamp <= PREVIEW_INSPECTOR_HEALTH_ERROR_CHAIN_MS &&
    previousRoot.message !== message;
  const event = isStyledComponentsInstanceWarning
    ? 'styled-components-instance-warning'
    : followsRoot
      ? hasFallbackEvidence ? 'runtime-error-fallback' : 'runtime-error-cascade'
      : 'runtime-error-root';
  const parentEventId = followsRoot ? previousRoot.eventId : undefined;
  const eventId = recordPreviewInspectorRuntimeHealth({
    category: 'runtime-error',
    detail: {
      componentStack: componentStack.slice(0, PREVIEW_INSPECTOR_HEALTH_TEXT_LIMIT),
      confidence: isStyledComponentsInstanceWarning
        ? 'package-runtime-warning'
        : followsRoot
          ? hasFallbackEvidence ? 'stack-evidenced' : 'temporal'
          : 'root',
      location: typeof entry.location === 'string' ? entry.location : undefined,
      message,
      phase: typeof entry.phase === 'string' ? entry.phase : undefined,
      source,
    },
    event,
    parentEventId,
  });
  if (!isStyledComponentsInstanceWarning && !followsRoot && eventId !== undefined) {
    previewInspectorSession.runtimeHealthRootErrors.set(key, { eventId, message, timestamp: now });
    if (previewInspectorSession.runtimeHealthRootErrors.size > PREVIEW_INSPECTOR_HEALTH_ERROR_ROOT_LIMIT) {
      previewInspectorSession.runtimeHealthRootErrors.delete(
        previewInspectorSession.runtimeHealthRootErrors.keys().next().value,
      );
    }
  }
}
`;
}
