/**
 * Supplies the isolated CSS used by the debugger-style render-flow chart.
 *
 * The companion Inspector sanitizes inline styles before mirroring controls into its editor tab.
 * Consequently, the chart is expressed entirely through semantic classes and repeated rank/lane
 * cells. No project CSS, measured DOM geometry, SVG, or unsafe style attribute is required.
 */

/**
 * Creates the flowchart-only stylesheet appended to the shared Page Inspector stylesheet.
 *
 * Fixed lane and connector dimensions keep orthogonal edges aligned in both the hidden authoritative
 * Inspector and its independently laid-out companion clone. Narrow viewports retain the dimensions
 * and scroll on both axes instead of compressing branch labels or component names.
 *
 * @returns CSS scoped by the Inspector Shadow Root's existing `.rpi-*` namespace.
 */
export function createPreviewInspectorFlowchartCssRuntimeSource(): string {
  return [
    '.rpi-flowchart{display:grid;gap:8px;grid-template-rows:auto minmax(260px,1fr);height:100%;max-width:100%;min-height:0;min-width:0}',
    '.rpi-flowchart-toolbar{align-items:center;border-bottom:1px solid var(--rpi-border);display:flex;flex-wrap:wrap;gap:6px;',
    'max-width:100%;min-width:0;padding:6px 8px}.rpi-flowchart-toolbar-heading{display:flex;flex:1 1 180px;flex-wrap:wrap;gap:6px;min-width:0}',
    '.rpi-flowchart-legend{display:flex;flex:2 1 320px;flex-wrap:wrap;gap:4px;min-width:0}',
    '.rpi-flowchart-legend-item{border:1px solid var(--rpi-border);border-radius:999px;color:var(--rpi-muted);font-size:8px;',
    'font-weight:700;max-width:100%;overflow:hidden;padding:1px 5px;text-overflow:ellipsis;white-space:nowrap}',
    '.rpi-flowchart-legend-item[data-rpi-legend-kind="blocker"]{color:var(--vscode-errorForeground,#f48771)}',
    '.rpi-flowchart-legend-item[data-rpi-legend-kind="current"]{color:var(--vscode-charts-yellow,#cca700)}',
    '.rpi-flowchart-legend-item[data-rpi-legend-kind="inferred"]{border-style:dashed}',
    '.rpi-flowchart-camera{display:flex;flex:0 1 auto;flex-wrap:wrap;gap:3px;justify-content:flex-end;min-width:0}',
    '.rpi-flowchart-camera-button{min-width:28px}.rpi-flowchart-zoom-label{font-variant-numeric:tabular-nums;min-width:48px}',
    '.rpi-flowchart-camera-status{color:var(--rpi-muted);flex:1 1 100%;font-size:9px;overflow-wrap:anywhere}',
    '.rpi-flowchart-locate-button[data-rpi-locator-status="blocked"]{border-color:var(--vscode-errorForeground,#f48771)}',
    '.rpi-flowchart-viewport{border:1px solid var(--rpi-border);border-radius:4px;max-width:100%;',
    'min-height:260px;min-width:0;overflow:auto;overscroll-behavior:contain;scrollbar-gutter:stable}',
    '.rpi-flowchart-canvas{align-items:start;display:grid;grid-auto-flow:column;grid-auto-columns:max-content;',
    'isolation:isolate;min-height:100%;min-width:100%;padding:8px;width:max-content}',
    '.rpi-flowchart-rank{display:grid;grid-template-rows:22px auto;min-width:224px;position:relative;z-index:2}',
    '.rpi-flowchart-rank-label{color:var(--rpi-muted);font-size:9px;font-weight:750;letter-spacing:.05em;',
    'overflow:hidden;padding:2px 7px;text-overflow:ellipsis;text-transform:uppercase;white-space:nowrap}',
    '.rpi-flowchart-rank-lanes,.rpi-flowchart-edge-track{display:grid;grid-auto-rows:104px}',
    '.rpi-flowchart-lane{align-items:center;display:flex;justify-content:center;min-height:104px;padding:6px}',
    '.rpi-flowchart-node{align-items:start;background:var(--vscode-editor-background,#1e1e1e);',
    'border:1px solid var(--rpi-border);border-radius:5px;color:inherit;cursor:pointer;display:grid;gap:5px;',
    'grid-template-columns:24px minmax(0,1fr);height:88px;max-width:212px;min-width:212px;overflow:hidden;',
    'padding:8px;text-align:left;width:212px}',
    '.rpi-flowchart-node:hover{background:var(--vscode-list-hoverBackground,#2a2d2e)}',
    '.rpi-flowchart-node:focus-visible{outline:2px solid var(--vscode-focusBorder,#007fd4);outline-offset:1px}',
    '.rpi-flowchart-node[aria-pressed="true"]{box-shadow:0 0 0 2px var(--vscode-focusBorder,#007fd4)}',
    '.rpi-flowchart-node[data-rpi-branch-state="inactive"]{border-style:dashed;opacity:.62}',
    '.rpi-flowchart-node[data-rpi-flow-status="active"]{border-color:var(--vscode-errorForeground,#f48771)}',
    '.rpi-flowchart-node[data-rpi-flow-status="resolved"]{border-color:var(--vscode-testing-iconPassed,#73c991)}',
    '.rpi-flowchart-node[data-rpi-flow-status="waiting"]{opacity:.55}',
    '.rpi-flowchart-node[data-rpi-graph-kind="entry"],.rpi-flowchart-node[data-rpi-graph-kind="return"]{border-radius:999px}',
    '.rpi-flowchart-node[data-rpi-graph-kind="decision"]{clip-path:polygon(8% 0,92% 0,100% 50%,92% 100%,8% 100%,0 50%);',
    'padding-left:16px;padding-right:16px}',
    '.rpi-flowchart-node[data-rpi-graph-kind="join"]{align-items:center;border-radius:50%;display:flex;height:52px;',
    'justify-content:center;min-width:52px;padding:5px;width:52px}',
    '.rpi-flowchart-node[data-rpi-graph-kind="hoc"]{border-style:double;border-width:3px}',
    '.rpi-flowchart-node[data-rpi-graph-kind="component-slot"]{clip-path:polygon(7% 0,100% 0,93% 100%,0 100%);',
    'padding-left:15px;padding-right:15px}',
    '.rpi-flowchart-node[data-rpi-graph-kind="blocker"]{clip-path:polygon(8% 0,92% 0,100% 18%,100% 82%,92% 100%,8% 100%,0 82%,0 18%)}',
    '.rpi-flowchart-node[data-rpi-current-file-blocker="true"]{background:color-mix(in srgb,var(--vscode-charts-yellow,#cca700) 10%,',
    'var(--vscode-editor-background,#1e1e1e));box-shadow:inset 4px 0 0 var(--vscode-charts-yellow,#cca700)}',
    '.rpi-flowchart-node[data-rpi-current-file="true"]{border-color:var(--vscode-charts-yellow,#cca700);',
    'box-shadow:inset 0 0 0 1px color-mix(in srgb,var(--vscode-charts-yellow,#cca700) 70%,transparent)}',
    '.rpi-flowchart-node[data-rpi-current-file-context="true"][data-rpi-current-file="false"]{border-color:color-mix(in srgb,',
    'var(--vscode-charts-yellow,#cca700) 56%,var(--rpi-border));border-style:dashed}',
    '.rpi-flowchart-node[data-rpi-current-file="true"][aria-pressed="true"]{box-shadow:0 0 0 2px var(--vscode-charts-yellow,#cca700)}',
    '.rpi-flowchart-node-symbol{align-items:center;background:var(--vscode-badge-background,#4d4d4d);border-radius:50%;',
    'color:var(--vscode-badge-foreground,#fff);display:flex;font-size:10px;font-weight:800;height:23px;',
    'justify-content:center;width:23px}',
    '.rpi-flowchart-node[data-rpi-graph-kind="join"] .rpi-flowchart-node-symbol{margin:0}',
    '.rpi-flowchart-node-copy{display:grid;gap:2px;min-width:0}.rpi-flowchart-node-heading{align-items:center;',
    'display:flex;gap:4px;min-width:0}.rpi-flowchart-node-heading>strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
    '.rpi-flowchart-node-target{color:var(--vscode-charts-yellow,#cca700);font-size:7px;font-weight:850;margin-left:auto;white-space:nowrap}',
    '.rpi-flowchart-node-target[data-rpi-estimated="true"],.rpi-current-file-badge[data-rpi-estimated="true"]{opacity:.72}',
    '.rpi-flowchart-node-kind,.rpi-flowchart-node-state,.rpi-flowchart-node-owner{font-size:9px;overflow:hidden;',
    'text-overflow:ellipsis;white-space:nowrap}.rpi-flowchart-node-kind{color:var(--vscode-textLink-foreground,#3794ff);font-weight:750}',
    '.rpi-flowchart-node-state,.rpi-flowchart-node-owner{color:var(--rpi-muted)}',
    '.rpi-flowchart-node-branch{color:var(--vscode-charts-yellow,#cca700);font-size:9px;font-weight:750;',
    'overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
    '.rpi-flowchart-connector{display:grid;grid-template-rows:22px auto;min-width:126px;position:relative;z-index:1}',
    '.rpi-flowchart-connector-label{color:var(--rpi-muted);font-size:8px;padding-top:2px;text-align:center;text-transform:uppercase}',
    '.rpi-flowchart-edge-stack{display:grid;min-width:126px}.rpi-flowchart-edge-track{grid-area:1/1;pointer-events:none;position:relative}',
    '.rpi-flowchart-edge-cell{--rpi-edge-color:var(--vscode-focusBorder,#007fd4);--rpi-edge-x:50%;',
    'min-height:104px;position:relative}.rpi-flowchart-edge-track[data-rpi-active="false"] .rpi-flowchart-edge-cell{',
    '--rpi-edge-color:var(--vscode-panel-border,#666)}',
    '.rpi-flowchart-edge-track[data-rpi-certainty="conditional"] .rpi-flowchart-edge-cell::before,',
    '.rpi-flowchart-edge-track[data-rpi-certainty="conditional"] .rpi-flowchart-edge-cell::after{border-style:dashed}',
    '.rpi-flowchart-edge-cell::before,.rpi-flowchart-edge-cell::after{border-color:var(--rpi-edge-color);content:"";',
    'pointer-events:none;position:absolute}',
    '.rpi-flowchart-edge-cell[data-rpi-path="straight"]::before{border-top:2px solid var(--rpi-edge-color);left:0;right:0;top:50%}',
    '.rpi-flowchart-edge-cell[data-rpi-path="start-down"]::before,.rpi-flowchart-edge-cell[data-rpi-path="start-up"]::before{',
    'border-top:2px solid var(--rpi-edge-color);left:0;right:calc(100% - var(--rpi-edge-x));top:50%}',
    '.rpi-flowchart-edge-cell[data-rpi-path="start-down"]::after{border-left:2px solid var(--rpi-edge-color);bottom:0;',
    'left:var(--rpi-edge-x);top:50%}',
    '.rpi-flowchart-edge-cell[data-rpi-path="start-up"]::after{border-left:2px solid var(--rpi-edge-color);bottom:50%;',
    'left:var(--rpi-edge-x);top:0}',
    '.rpi-flowchart-edge-cell[data-rpi-path="vertical"]::after{border-left:2px solid var(--rpi-edge-color);bottom:0;',
    'left:var(--rpi-edge-x);top:0}',
    '.rpi-flowchart-edge-cell[data-rpi-path="end-down"]::before,.rpi-flowchart-edge-cell[data-rpi-path="end-up"]::before{',
    'border-top:2px solid var(--rpi-edge-color);left:var(--rpi-edge-x);right:0;top:50%}',
    '.rpi-flowchart-edge-cell[data-rpi-path="end-down"]::after{border-left:2px solid var(--rpi-edge-color);bottom:50%;',
    'left:var(--rpi-edge-x);top:0}',
    '.rpi-flowchart-edge-cell[data-rpi-path="end-up"]::after{border-left:2px solid var(--rpi-edge-color);bottom:0;',
    'left:var(--rpi-edge-x);top:50%}',
    '.rpi-flowchart-edge-arrow{color:var(--rpi-edge-color);font-size:14px;font-weight:900;line-height:14px;',
    'position:absolute;right:-1px;top:calc(50% - 7px)}',
    '.rpi-flowchart-edge-label{background:var(--vscode-editor-background,#1e1e1e);border:1px solid var(--rpi-edge-color);',
    'border-radius:8px;color:inherit;font-size:8px;font-weight:750;left:2px;max-width:118px;overflow:hidden;',
    'padding:0 4px;position:absolute;text-overflow:ellipsis;top:2px;white-space:nowrap;z-index:2}',
    '.rpi-flowchart-edge-track[data-rpi-track="1"]{--rpi-edge-x:24%}.rpi-flowchart-edge-track[data-rpi-track="2"]{--rpi-edge-x:32%}',
    '.rpi-flowchart-edge-track[data-rpi-track="3"]{--rpi-edge-x:40%}.rpi-flowchart-edge-track[data-rpi-track="4"]{--rpi-edge-x:56%}',
    '.rpi-flowchart-edge-track[data-rpi-track="5"]{--rpi-edge-x:64%}.rpi-flowchart-edge-track[data-rpi-track="6"]{--rpi-edge-x:72%}',
    '.rpi-flowchart-edge-track[data-rpi-track="7"]{--rpi-edge-x:80%}',
    '.rpi-flowchart-edge-track[data-rpi-track="1"] .rpi-flowchart-edge-label{top:13px}',
    '.rpi-flowchart-edge-track[data-rpi-track="2"] .rpi-flowchart-edge-label{top:24px}',
    '.rpi-flowchart-edge-track[data-rpi-track="3"] .rpi-flowchart-edge-label{top:35px}',
    '.rpi-flowchart-edge-track[data-rpi-track="4"] .rpi-flowchart-edge-label{top:46px}',
    '.rpi-flowchart-edge-track[data-rpi-track="5"] .rpi-flowchart-edge-label{top:57px}',
    '.rpi-flowchart-edge-track[data-rpi-track="6"] .rpi-flowchart-edge-label{top:68px}',
    '.rpi-flowchart-edge-track[data-rpi-track="7"] .rpi-flowchart-edge-label{top:79px}',
    '.rpi-flowchart-overflow{color:var(--rpi-muted);font-size:9px;padding:4px 8px;text-align:center}',
    '.rpi-flow-inspector{display:grid;grid-template-rows:auto minmax(0,1fr);height:100%;max-width:100%;min-height:0;min-width:0;overflow:hidden}',
    '.rpi-flow-inspector-heading{align-items:center;background:var(--vscode-sideBarSectionHeader-background,rgba(128,128,128,.08));',
    'border-bottom:1px solid var(--rpi-border);display:flex;gap:8px;justify-content:space-between;min-width:0;padding:8px}',
    '.rpi-flow-inspector-heading-copy{display:grid;min-width:0}.rpi-flow-inspector-heading-copy>strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
    '.rpi-flow-inspector-kicker,.rpi-flow-inspector-section-title{color:var(--vscode-textLink-foreground,#3794ff);font-size:8px;',
    'font-weight:850;letter-spacing:.08em;text-transform:uppercase}',
    '.rpi-flow-inspector-scroll{align-content:start;display:grid;gap:9px;min-height:0;min-width:0;overflow:auto;',
    'overscroll-behavior:contain;padding:9px;scrollbar-gutter:stable}',
    '.rpi-flow-inspector-selected-summary,.rpi-flow-inspector-relations,.rpi-flow-inspector-selected-editor,',
    '.rpi-flow-inspector-locate-guide{border:1px solid var(--rpi-border);border-radius:4px;display:grid;gap:7px;min-width:0;padding:8px}',
    '.rpi-flow-inspector-selected-badges{display:flex;flex-wrap:wrap;gap:3px;min-width:0}',
    '.rpi-flow-inspector-selected-name{font-size:13px;overflow-wrap:anywhere}.rpi-flow-inspector-owner{display:grid;gap:2px;min-width:0}',
    '.rpi-flow-inspector-owner>span{color:var(--rpi-muted);font-size:10px;overflow-wrap:anywhere}',
    '.rpi-flow-inspector-guide-heading{align-items:center;display:flex;flex-wrap:wrap;gap:6px;justify-content:space-between}',
    '.rpi-flow-inspector-locate-summary{font-weight:700;overflow-wrap:anywhere}',
    '.rpi-flow-inspector-guide-steps{display:grid;gap:5px;list-style:none;margin:0;padding:0}',
    '.rpi-flow-inspector-guide-steps>li{align-items:start;border:1px solid var(--rpi-border);border-radius:3px;display:grid;gap:7px;',
    'grid-template-columns:22px minmax(0,1fr);padding:6px}.rpi-flow-inspector-guide-index{align-items:center;background:var(--vscode-textLink-foreground,#3794ff);',
    'border-radius:50%;color:var(--vscode-editor-background,#111);display:flex;font-size:9px;font-weight:850;height:20px;justify-content:center;width:20px}',
    '.rpi-flow-inspector-guide-copy{display:grid;gap:1px;min-width:0}.rpi-flow-inspector-guide-copy>span{color:var(--rpi-muted);font-size:10px;overflow-wrap:anywhere}',
    '.rpi-flow-inspector .rpi-actions{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(160px,100%),1fr));min-width:0}',
    '.rpi-flow-inspector .rpi-actions>.rpi-button{min-width:0;overflow:hidden;text-align:left;text-overflow:ellipsis;white-space:normal;width:100%}',
    '.rpi-flow-inspector-selected-editor,.rpi-flow-inspector-selected-editor>*{max-width:100%;min-width:0}',
    '.rpi-flow-inspector-selected-editor .rpi-flow-condition-controls{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(128px,100%),1fr))}',
    '.rpi-flow-inspector-selected-editor .rpi-flow-condition-state{grid-column:1/-1;min-width:0}',
    '.rpi-flow-inspector-selected-editor .rpi-json{max-width:100%;min-width:0;width:100%}',
    '.rpi-flow-inspector[data-rpi-collapsed="true"]{grid-template-rows:auto}.rpi-flow-inspector [data-rpi-active-path="false"]{border-style:dashed;opacity:.72}',
    '.rpi-current-file-badge{color:var(--vscode-charts-yellow,#cca700);font-weight:850}',
    '.rpi-visually-hidden{clip:rect(0 0 0 0);clip-path:inset(50%);height:1px;overflow:hidden;position:absolute;',
    'white-space:nowrap;width:1px}',
    '@container rpi-inspector (max-width:760px){.rpi-flowchart{grid-template-rows:auto minmax(96px,1fr)}',
    '.rpi-flowchart-viewport{min-height:96px}.rpi-flowchart-toolbar{align-items:stretch}.rpi-flowchart-camera{justify-content:flex-start}',
    '.rpi-flowchart-locate-button{flex:1 1 150px}.rpi-flow-inspector-heading{align-items:flex-start}',
    '.rpi-flow-inspector-scroll{padding:7px}.rpi-flow-inspector-selected-summary,.rpi-flow-inspector-relations,',
    '.rpi-flow-inspector-selected-editor,.rpi-flow-inspector-locate-guide{padding:7px}}',
    '@container rpi-inspector (max-width:460px){.rpi-flowchart-toolbar-heading{flex-basis:100%}.rpi-flowchart-rank{min-width:202px}.rpi-flowchart-node{',
    'max-width:190px;min-width:190px;width:190px}.rpi-flowchart-connector{min-width:108px}.rpi-flowchart-edge-stack{min-width:108px}',
    '.rpi-flowchart-camera{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));width:100%}',
    '.rpi-flowchart-camera>.rpi-button{min-width:0;width:100%}.rpi-flowchart-locate-button{grid-column:1/-1;grid-row:3}',
    '.rpi-flowchart-inspector-toggle{grid-column:3;grid-row:2}.rpi-flowchart-legend{display:none}',
    '.rpi-flowchart{grid-template-rows:auto minmax(0,1fr)}.rpi-flowchart-viewport{min-height:0}',
    '.rpi-flow-inspector-heading{gap:5px;padding:6px}.rpi-flow-inspector-heading-copy>strong{white-space:normal;overflow-wrap:anywhere}',
    '.rpi-flow-inspector-scroll{gap:6px;padding:5px}.rpi-flow-inspector-guide-heading>.rpi-button{flex:1 1 100%;width:100%}',
    '.rpi-flow-inspector-guide-steps>li{gap:5px;grid-template-columns:18px minmax(0,1fr);padding:5px}',
    '.rpi-flow-inspector-guide-index{height:18px;width:18px}.rpi-flow-inspector-selected-summary,',
    '.rpi-flow-inspector-relations,.rpi-flow-inspector-selected-editor,.rpi-flow-inspector-locate-guide{gap:5px;padding:6px}}',
    '@container rpi-inspector (max-width:320px){.rpi-flowchart-camera{grid-template-columns:repeat(2,minmax(0,1fr))}',
    '.rpi-flowchart-locate-button{grid-column:1/-1;grid-row:4}.rpi-flowchart-inspector-toggle{grid-column:2;grid-row:3}',
    '.rpi-flow-inspector-selected-badges{gap:2px}',
    '.rpi-flow-inspector .rpi-badge{max-width:100%;overflow:hidden;text-overflow:ellipsis}}',
    '@media(max-height:520px){.rpi-flowchart{grid-template-rows:auto minmax(72px,1fr)}.rpi-flowchart-viewport{min-height:72px}}',
    '@media(max-height:520px){@container rpi-inspector (max-width:460px){.rpi-flowchart{grid-template-rows:auto minmax(0,1fr)}',
    '.rpi-flowchart-viewport{min-height:0}}}',
    '@media(prefers-reduced-motion:reduce){.rpi-flowchart-node{scroll-behavior:auto}}',
  ].join('');
}
