/** Verifies evidence-backed placeholders for absent tsconfig-aliased generated UI source trees. */
import { mkdir, mkdtemp, realpath, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import vm from 'node:vm';
import { build, type Plugin } from 'esbuild';
import { describe, expect, it, vi } from 'vitest';
import { createPreviewGeneratedUiFallbackPlugin } from '../../../src/adapters/esbuild/previewGeneratedUiFallbackPlugin';
import { createPreviewStaticModuleResolver } from '../../../src/adapters/esbuild/previewStaticModuleResolver';

describe('generated UI preview fallback', () => {
  /** Keeps generated design-system children visible and supplies neutral styling helpers. */
  it('renders aliased generated UI placeholders when a nearby marker proves generation', async () => {
    const workspaceRoot = await mkdtemp(path.join(tmpdir(), 'react-preview-generated-ui-'));
    const appRoot = path.join(workspaceRoot, 'apps', 'site');
    const entryPath = path.join(appRoot, 'src', 'Page.tsx');
    try {
      await Promise.all([
        mkdir(path.dirname(entryPath), { recursive: true }),
        mkdir(path.join(appRoot, 'styles'), { recursive: true }),
      ]);
      await Promise.all([
        writeAliasConfig(appRoot),
        writeFile(
          path.join(appRoot, 'styles', 'README.md'),
          'These styles are autogenerated by the registry build process and gitignored.',
          'utf8',
        ),
        writeFile(
          entryPath,
          [
            "import * as React from 'react';",
            "import { Button, Dialog, DialogContent, buttonVariants, useGenerated } from '@/styles/theme/ui/button';",
            "import { Card } from '@/styles/theme/ui/card';",
            'let heavyCalls = 0;',
            "const Heavy = () => { heavyCalls += 1; return React.createElement('span', null, 'heavy'); };",
            'const closedDialog = React.__render(React.createElement(Dialog, { open: false }, React.createElement(DialogContent, null, React.createElement(Heavy))));',
            'const openDialog = React.__render(React.createElement(Dialog, { open: true }, React.createElement(DialogContent, null, React.createElement(Heavy))));',
            'export const result = {',
            "  button: Button({ children: 'Continue', id: 'next', variant: 'primary' }),",
            "  header: Card.Header({ children: 'Summary' }),",
            "  classes: buttonVariants({ variant: 'primary' }),",
            '  closedDialog,',
            '  openDialog,',
            '  heavyCalls,',
            '  stableHookValue: useGenerated() === useGenerated(),',
            '  blockedCompound: Button.WrappedComponent,',
            '  boundedCompound: Button.A?.B?.C?.D?.E?.F?.G,',
            '  prototypeKinds: [typeof Button.prototype, typeof Card.Header.prototype],',
            '  classMarkers: [Button.prototype.isReactComponent, Card.Header.prototype.isReactComponent],',
            '  reactStatics: [Button.childContextTypes, Button.getDerivedStateFromProps, Card.contextTypes],',
            '};',
          ].join('\n'),
          'utf8',
        ),
      ]);

      const resolver = createPreviewStaticModuleResolver({ workspaceRoot });
      expect(resolver.resolveMissingPathAliasCandidate('@/styles/theme/ui/button', entryPath)).toBe(
        path.join(await realpath(path.join(appRoot, 'styles')), 'theme', 'ui', 'button'),
      );
      const watchedDirectories: string[] = [];
      const result = await buildFixture(entryPath, workspaceRoot, [
        createPreviewGeneratedUiFallbackPlugin({
          registerWatchDirectory: (directoryPath) => watchedDirectories.push(directoryPath),
          staticModuleResolver: resolver,
          workspaceRoot,
        }),
        createReactFixturePlugin(),
      ]);
      const exports = executeCommonJs(result.outputFiles?.[0]?.text ?? '') as {
        readonly result: {
          readonly button: { readonly props: Record<string, unknown> };
          readonly blockedCompound: unknown;
          readonly boundedCompound: unknown;
          readonly closedDialog: { readonly children: readonly unknown[] };
          readonly classes: unknown;
          readonly header: unknown;
          readonly heavyCalls: number;
          readonly openDialog: unknown;
          readonly stableHookValue: boolean;
          readonly classMarkers: readonly unknown[];
          readonly prototypeKinds: readonly string[];
          readonly reactStatics: readonly unknown[];
        };
      };

      expect(exports.result.button).toMatchObject({
        children: ['Continue'],
        props: {
          'data-react-preview-generated-component': 'Button',
          id: 'next',
        },
        tag: 'button',
      });
      expect(exports.result.button.props).not.toHaveProperty('variant');
      expect(exports.result.header).toMatchObject({
        children: ['Summary'],
        props: { 'data-react-preview-generated-component': 'Card.Header' },
        tag: 'div',
      });
      expect(exports.result.classes).toBe('');
      expect(JSON.stringify(exports.result.closedDialog)).not.toContain('heavy');
      expect(JSON.stringify(exports.result.closedDialog)).toContain(
        'data-react-preview-generated-overlay',
      );
      expect(JSON.stringify(exports.result.openDialog)).toContain('heavy');
      expect(exports.result.heavyCalls).toBe(1);
      expect(exports.result.stableHookValue).toBe(true);
      expect(exports.result.blockedCompound).toBeUndefined();
      expect(exports.result.boundedCompound).toBeUndefined();
      expect(exports.result.prototypeKinds).toEqual(['object', 'object']);
      expect(exports.result.classMarkers).toEqual([undefined, undefined]);
      expect(exports.result.reactStatics).toEqual([undefined, undefined, undefined]);
      expect(result.warnings).toHaveLength(1);
      expect(result.warnings[0]?.text).toContain('Generated project UI source');
      expect(new Set(watchedDirectories)).toEqual(
        new Set([await realpath(path.join(appRoot, 'styles'))]),
      );
    } finally {
      await rm(workspaceRoot, { force: true, recursive: true });
    }
  });

  /** Propagates downstream named demand through an authored star barrel without a workspace scan. */
  it('exposes generated UI names re-exported through an authored star barrel', async () => {
    const workspaceRoot = await mkdtemp(path.join(tmpdir(), 'react-preview-generated-barrel-ui-'));
    const appRoot = path.join(workspaceRoot, 'app');
    const entryPath = path.join(appRoot, 'src', 'Page.tsx');
    const barrelPath = path.join(appRoot, 'src', 'barrel.ts');
    try {
      await Promise.all([
        mkdir(path.dirname(entryPath), { recursive: true }),
        mkdir(path.join(appRoot, 'styles'), { recursive: true }),
      ]);
      await Promise.all([
        writeAliasConfig(appRoot),
        writeFile(
          path.join(appRoot, 'styles', 'README.md'),
          'This UI tree is autogenerated by the registry build process and gitignored.',
          'utf8',
        ),
        writeFile(barrelPath, "export * from '@/styles/theme/ui/button';", 'utf8'),
        writeFile(
          entryPath,
          [
            "import { Button } from './barrel';",
            "export const result = Button({ children: 'From barrel' });",
          ].join('\n'),
          'utf8',
        ),
      ]);
      const resolver = createPreviewStaticModuleResolver({ workspaceRoot });
      const result = await buildFixture(entryPath, workspaceRoot, [
        createPreviewGeneratedUiFallbackPlugin({
          staticModuleResolver: resolver,
          workspaceRoot,
        }),
        createReactFixturePlugin(),
      ]);
      const exports = executeCommonJs(result.outputFiles?.[0]?.text ?? '') as {
        readonly result: { readonly props: Record<string, unknown>; readonly tag: string };
      };

      expect(exports.result).toMatchObject({
        children: ['From barrel'],
        props: { 'data-react-preview-generated-component': 'Button' },
        tag: 'button',
      });
      expect(result.warnings).toHaveLength(1);
    } finally {
      await rm(workspaceRoot, { force: true, recursive: true });
    }
  });

  /** Refuses an ordinary missing alias when no bounded marker explicitly proves generated output. */
  it('leaves unproven missing aliases as build errors', async () => {
    const workspaceRoot = await mkdtemp(path.join(tmpdir(), 'react-preview-unproven-ui-'));
    const appRoot = path.join(workspaceRoot, 'app');
    const entryPath = path.join(appRoot, 'src', 'Page.tsx');
    try {
      await Promise.all([
        mkdir(path.dirname(entryPath), { recursive: true }),
        mkdir(path.join(appRoot, 'styles'), { recursive: true }),
      ]);
      await Promise.all([
        writeAliasConfig(appRoot),
        writeFile(
          path.join(appRoot, 'styles', 'README.md'),
          'Hand-authored application styles live here.',
          'utf8',
        ),
        writeFile(
          entryPath,
          "import { Missing } from '@/styles/ui/missing'; export default Missing;",
          'utf8',
        ),
      ]);
      const resolver = createPreviewStaticModuleResolver({ workspaceRoot });

      await expect(
        buildFixture(entryPath, workspaceRoot, [
          createPreviewGeneratedUiFallbackPlugin({
            staticModuleResolver: resolver,
            workspaceRoot,
          }),
        ]),
      ).rejects.toThrow('Could not resolve "@/styles/ui/missing"');
    } finally {
      await rm(workspaceRoot, { force: true, recursive: true });
    }
  });

  /** Preserves normal authored source even when its parent directory documents generated siblings. */
  it('keeps existing aliased source on normal esbuild resolution', async () => {
    const workspaceRoot = await mkdtemp(path.join(tmpdir(), 'react-preview-existing-ui-'));
    const appRoot = path.join(workspaceRoot, 'app');
    const entryPath = path.join(appRoot, 'src', 'Page.ts');
    const componentPath = path.join(appRoot, 'styles', 'ui', 'button.ts');
    try {
      await Promise.all([
        mkdir(path.dirname(entryPath), { recursive: true }),
        mkdir(path.dirname(componentPath), { recursive: true }),
      ]);
      await Promise.all([
        writeAliasConfig(appRoot),
        writeFile(
          path.join(appRoot, 'styles', 'README.md'),
          'This tree is autogenerated by a documented build process.',
          'utf8',
        ),
        writeFile(componentPath, "export const Button = 'authored';", 'utf8'),
        writeFile(
          entryPath,
          "import { Button } from '@/styles/ui/button'; export const result = Button;",
          'utf8',
        ),
      ]);
      const resolver = createPreviewStaticModuleResolver({ workspaceRoot });
      const result = await buildFixture(entryPath, workspaceRoot, [
        createPreviewGeneratedUiFallbackPlugin({
          staticModuleResolver: resolver,
          workspaceRoot,
        }),
      ]);
      const exports = executeCommonJs(result.outputFiles?.[0]?.text ?? '');

      expect(exports.result).toBe('authored');
      expect(result.warnings).toHaveLength(0);
    } finally {
      await rm(workspaceRoot, { force: true, recursive: true });
    }
  });

  /** Rejects a lexical workspace alias whose nearest real ancestor is an external symlink. */
  it('does not read generated markers or watch paths outside the workspace through symlinks', async () => {
    const workspaceRoot = await mkdtemp(path.join(tmpdir(), 'react-preview-generated-link-'));
    const externalRoot = await mkdtemp(path.join(tmpdir(), 'react-preview-generated-external-'));
    const appRoot = path.join(workspaceRoot, 'app');
    const entryPath = path.join(appRoot, 'src', 'Page.tsx');
    try {
      await mkdir(path.dirname(entryPath), { recursive: true });
      await Promise.all([
        writeAliasConfig(appRoot),
        writeFile(
          path.join(externalRoot, 'README.md'),
          'This source is autogenerated by the build process and gitignored.',
          'utf8',
        ),
        writeFile(
          entryPath,
          "import { Button } from '@/styles/ui/button'; export default Button;",
          'utf8',
        ),
      ]);
      await symlink(externalRoot, path.join(appRoot, 'styles'));
      const resolver = createPreviewStaticModuleResolver({ workspaceRoot });
      const registerWatchDirectory = vi.fn();

      expect(
        resolver.resolveMissingPathAliasCandidate('@/styles/ui/button', entryPath),
      ).toBeUndefined();
      await expect(
        buildFixture(entryPath, workspaceRoot, [
          createPreviewGeneratedUiFallbackPlugin({
            registerWatchDirectory,
            staticModuleResolver: resolver,
            workspaceRoot,
          }),
        ]),
      ).rejects.toThrow('Could not resolve "@/styles/ui/button"');
      expect(registerWatchDirectory).not.toHaveBeenCalled();
    } finally {
      await Promise.all([
        rm(workspaceRoot, { force: true, recursive: true }),
        rm(externalRoot, { force: true, recursive: true }),
      ]);
    }
  });
});

/** Writes the nearest project config used by both esbuild and the preview's static resolver. */
async function writeAliasConfig(appRoot: string): Promise<void> {
  await writeFile(
    path.join(appRoot, 'tsconfig.json'),
    JSON.stringify({
      compilerOptions: { baseUrl: '.', jsx: 'react-jsx', paths: { '@/*': ['./*'] } },
    }),
    'utf8',
  );
}

/** Runs one file-backed browser bundle entirely in memory. */
async function buildFixture(
  entryPath: string,
  workspaceRoot: string,
  plugins: readonly Plugin[],
): Promise<Awaited<ReturnType<typeof build>>> {
  return await build({
    absWorkingDir: workspaceRoot,
    bundle: true,
    entryPoints: [entryPath],
    format: 'cjs',
    logLevel: 'silent',
    plugins: [...plugins],
    write: false,
  });
}

/** Supplies only the React element operations exercised by generated structural placeholders. */
function createReactFixturePlugin(): Plugin {
  return {
    name: 'react-fixture',
    setup(buildContext): void {
      buildContext.onResolve({ filter: /^react$/ }, () => ({
        namespace: 'react-fixture',
        path: 'react',
      }));
      buildContext.onLoad({ filter: /.*/, namespace: 'react-fixture' }, () => ({
        contents: [
          'const contextValues = new Map();',
          'const render = (element) => {',
          "  if (element === null || typeof element !== 'object' || !('tag' in element)) return element;",
          "  const providerContext = typeof element.tag === 'function' ? Object.getOwnPropertyDescriptor(element.tag, '__previewContext')?.value : undefined;",
          '  if (providerContext !== undefined) {',
          '    const hadValue = contextValues.has(providerContext);',
          '    const previous = contextValues.get(providerContext);',
          '    contextValues.set(providerContext, element.props?.value);',
          '    const rendered = element.children.map(render);',
          '    if (hadValue) contextValues.set(providerContext, previous);',
          '    else contextValues.delete(providerContext);',
          '    return rendered.length === 1 ? rendered[0] : rendered;',
          '  }',
          "  if (typeof element.tag === 'function') return render(element.tag({ ...(element.props || {}), children: element.children.length === 1 ? element.children[0] : element.children }));",
          '  return { ...element, children: element.children.map(render) };',
          '};',
          'module.exports = {',
          '  __render: render,',
          '  createContext: (defaultValue) => {',
          '    const context = { defaultValue };',
          '    context.Provider = function Provider() {};',
          '    context.Provider.__previewContext = context;',
          '    return context;',
          '  },',
          '  createElement: (tag, props, ...children) => ({ children, props, tag }),',
          '  cloneElement: (element, props) => ({ ...element, props: { ...element.props, ...props } }),',
          "  isValidElement: (value) => Boolean(value && typeof value === 'object' && 'tag' in value),",
          '  useContext: (context) => contextValues.has(context) ? contextValues.get(context) : context.defaultValue,',
          '};',
        ].join('\n'),
        loader: 'js',
      }));
    },
  };
}

/** Evaluates a deterministic test bundle and returns its CommonJS exports. */
function executeCommonJs(sourceText: string): Record<string, unknown> {
  const module = { exports: {} as Record<string, unknown> };
  vm.runInNewContext(sourceText, { exports: module.exports, module });
  return module.exports;
}
