/** Verifies evidence-backed placeholders for absent tsconfig-aliased generated UI source trees. */
import { existsSync, unlinkSync } from 'node:fs';
import { mkdir, mkdtemp, realpath, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import vm from 'node:vm';
import { build, context, type Plugin } from 'esbuild';
import type ts from 'typescript';
import { describe, expect, it, vi } from 'vitest';
import { createPreviewGeneratedUiFallbackPlugin } from '../../../src/adapters/esbuild/previewGeneratedUiFallbackPlugin';
import { createPreviewStaticModuleResolver } from '../../../src/adapters/esbuild/previewStaticModuleResolver';

const typescriptTraversal = vi.hoisted(() => ({
  sourceFileVisits: vi.fn<(sourcePath: string) => void>(),
}));

vi.mock('typescript', async (importOriginal) => {
  const actual = await importOriginal<{ default: typeof import('typescript') }>();
  const compiler = actual.default;
  const instrumentedForEachChild: typeof compiler.forEachChild = <T>(
    node: ts.Node,
    callbackNode: (child: ts.Node) => T | undefined,
    callbackNodes?: (children: ts.NodeArray<ts.Node>) => T | undefined,
  ): T | undefined => {
    if (compiler.isSourceFile(node)) typescriptTraversal.sourceFileVisits(node.fileName);
    return compiler.forEachChild(node, callbackNode, callbackNodes);
  };
  return {
    ...actual,
    default: { ...compiler, forEachChild: instrumentedForEachChild },
  };
});

describe('generated UI preview fallback', () => {
  /** Keeps generated design-system children visible and supplies neutral styling helpers. */
  it('renders aliased generated UI placeholders when a nearby marker proves generation', async () => {
    const workspaceRoot = await mkdtemp(path.join(tmpdir(), 'react-preview-generated-ui-'));
    const appRoot = path.join(workspaceRoot, 'apps', 'site');
    const entryPath = path.join(appRoot, 'src', 'Page.tsx');
    try {
      await Promise.all([
        mkdir(path.dirname(entryPath), { recursive: true }),
        mkdir(path.join(appRoot, 'styles'), { recursive: true }),
      ]);
      await Promise.all([
        writeAliasConfig(appRoot),
        writeFile(
          path.join(appRoot, 'styles', 'README.md'),
          'These styles are autogenerated by the registry build process and gitignored.',
          'utf8',
        ),
        writeFile(
          entryPath,
          [
            "import * as React from 'react';",
            "import { Button, Dialog, DialogContent, buttonVariants, useGenerated } from '@/styles/theme/ui/button';",
            "import { Card } from '@/styles/theme/ui/card';",
            'let heavyCalls = 0;',
            "const Heavy = () => { heavyCalls += 1; return React.createElement('span', null, 'heavy'); };",
            'const closedDialog = React.__render(React.createElement(Dialog, { open: false }, React.createElement(DialogContent, null, React.createElement(Heavy))));',
            'const openDialog = React.__render(React.createElement(Dialog, { open: true }, React.createElement(DialogContent, null, React.createElement(Heavy))));',
            'export const result = {',
            "  button: Button({ children: 'Continue', id: 'next', variant: 'primary' }),",
            "  header: Card.Header({ children: 'Summary' }),",
            "  classes: buttonVariants({ variant: 'primary' }),",
            '  closedDialog,',
            '  openDialog,',
            '  heavyCalls,',
            '  stableHookValue: useGenerated() === useGenerated(),',
            '  blockedCompound: Button.WrappedComponent,',
            '  boundedCompound: Button.A?.B?.C?.D?.E?.F?.G,',
            '  prototypeKinds: [typeof Button.prototype, typeof Card.Header.prototype],',
            '  classMarkers: [Button.prototype.isReactComponent, Card.Header.prototype.isReactComponent],',
            '  reactStatics: [Button.childContextTypes, Button.getDerivedStateFromProps, Card.contextTypes],',
            '};',
          ].join('\n'),
          'utf8',
        ),
      ]);

      const resolver = createPreviewStaticModuleResolver({ workspaceRoot });
      expect(resolver.resolveMissingPathAliasCandidate('@/styles/theme/ui/button', entryPath)).toBe(
        path.join(await realpath(path.join(appRoot, 'styles')), 'theme', 'ui', 'button'),
      );
      const watchedDirectories: string[] = [];
      const result = await buildFixture(entryPath, workspaceRoot, [
        createPreviewGeneratedUiFallbackPlugin({
          registerWatchDirectory: (directoryPath) => watchedDirectories.push(directoryPath),
          staticModuleResolver: resolver,
          workspaceRoot,
        }),
        createReactFixturePlugin(),
      ]);
      const exports = executeCommonJs(result.outputFiles?.[0]?.text ?? '') as {
        readonly result: {
          readonly button: { readonly props: Record<string, unknown> };
          readonly blockedCompound: unknown;
          readonly boundedCompound: unknown;
          readonly closedDialog: { readonly children: readonly unknown[] };
          readonly classes: unknown;
          readonly header: unknown;
          readonly heavyCalls: number;
          readonly openDialog: unknown;
          readonly stableHookValue: boolean;
          readonly classMarkers: readonly unknown[];
          readonly prototypeKinds: readonly string[];
          readonly reactStatics: readonly unknown[];
        };
      };

      expect(exports.result.button).toMatchObject({
        children: ['Continue'],
        props: {
          'data-react-preview-generated-component': 'Button',
          id: 'next',
        },
        tag: 'button',
      });
      expect(exports.result.button.props).not.toHaveProperty('variant');
      expect(exports.result.header).toMatchObject({
        children: ['Summary'],
        props: { 'data-react-preview-generated-component': 'Card.Header' },
        tag: 'div',
      });
      expect(exports.result.classes).toBe('');
      expect(JSON.stringify(exports.result.closedDialog)).not.toContain('heavy');
      expect(JSON.stringify(exports.result.closedDialog)).toContain(
        'data-react-preview-generated-overlay',
      );
      expect(JSON.stringify(exports.result.openDialog)).toContain('heavy');
      expect(exports.result.heavyCalls).toBe(1);
      expect(exports.result.stableHookValue).toBe(true);
      expect(exports.result.blockedCompound).toBeUndefined();
      expect(exports.result.boundedCompound).toBeUndefined();
      expect(exports.result.prototypeKinds).toEqual(['object', 'object']);
      expect(exports.result.classMarkers).toEqual([undefined, undefined]);
      expect(exports.result.reactStatics).toEqual([undefined, undefined, undefined]);
      expect(result.warnings).toHaveLength(1);
      expect(result.warnings[0]?.text).toContain('Generated project UI source');
      expect(new Set(watchedDirectories)).toEqual(
        new Set([await realpath(path.join(appRoot, 'styles'))]),
      );
    } finally {
      await rm(workspaceRoot, { force: true, recursive: true });
    }
  });

  /** Adds recognizable role geometry while preserving authored wrapper and slotted-child styles. */
  it('applies conservative semantic styles without overriding authored inline values', async () => {
    const workspaceRoot = await mkdtemp(path.join(tmpdir(), 'react-preview-generated-visual-ui-'));
    const appRoot = path.join(workspaceRoot, 'app');
    const entryPath = path.join(appRoot, 'src', 'Page.tsx');
    try {
      await Promise.all([
        mkdir(path.dirname(entryPath), { recursive: true }),
        mkdir(path.join(appRoot, 'styles'), { recursive: true }),
      ]);
      await Promise.all([
        writeAliasConfig(appRoot),
        writeFile(
          path.join(appRoot, 'styles', 'README.md'),
          'This UI tree is autogenerated by the registry build process and gitignored.',
          'utf8',
        ),
        writeFile(
          entryPath,
          [
            "import * as React from 'react';",
            "import { AccordionTrigger, Badge, Button, Card, DialogContent, Input, PopoverContent, Skeleton, Spinner } from '@/styles/theme/ui/visuals';",
            'export const result = {',
            "  button: Button({ children: 'Save', style: { color: 'rebeccapurple', padding: '3rem' } }),",
            "  card: Card({ children: 'Summary', style: { borderRadius: '2rem' } }),",
            "  input: Input({ placeholder: 'Email', style: { backgroundColor: 'pink' } }),",
            "  badge: Badge({ children: 'New' }),",
            "  dialog: DialogContent({ children: 'Dialog', style: { width: '18rem' } }),",
            "  popover: PopoverContent({ children: 'Popover' }),",
            '  skeleton: Skeleton({}),',
            '  spinner: Spinner({}),',
            "  spinnerAuthored: Spinner({ style: { animation: 'none', borderRightColor: 'red' } }),",
            "  trigger: AccordionTrigger({ children: 'Question' }),",
            "  slotted: Button({ asChild: true, children: React.createElement('a', { style: { color: 'tomato' } }, 'Open') }),",
            '};',
          ].join('\n'),
          'utf8',
        ),
      ]);
      const resolver = createPreviewStaticModuleResolver({ workspaceRoot });
      const result = await buildFixture(entryPath, workspaceRoot, [
        createPreviewGeneratedUiFallbackPlugin({
          staticModuleResolver: resolver,
          workspaceRoot,
        }),
        createReactFixturePlugin(),
      ]);
      const injectedStyles: { id?: string; textContent?: string }[] = [];
      const previewDocument = {
        createElement: () => ({ id: '', textContent: '' }),
        getElementById: (id: string) => injectedStyles.find((style) => style.id === id) ?? null,
        head: {
          append: (style: { id?: string; textContent?: string }) => injectedStyles.push(style),
        },
      };
      const exports = executeCommonJs(result.outputFiles?.[0]?.text ?? '', {
        document: previewDocument,
      }) as {
        readonly result: Readonly<
          Record<
            | 'badge'
            | 'button'
            | 'card'
            | 'dialog'
            | 'input'
            | 'popover'
            | 'skeleton'
            | 'slotted'
            | 'spinner'
            | 'spinnerAuthored'
            | 'trigger',
            {
              readonly props: {
                readonly 'data-react-preview-generated-component': string;
                readonly style: Readonly<Record<string, unknown>>;
              };
              readonly tag: string;
            }
          >
        >;
      };

      expect(exports.result.button).toMatchObject({
        props: {
          'data-react-preview-generated-component': 'Button',
          style: {
            color: 'rebeccapurple',
            display: 'inline-flex',
            padding: '3rem',
          },
        },
        tag: 'button',
      });
      expect(exports.result.card.props.style).toMatchObject({
        backgroundColor: 'Canvas',
        border: '1px solid GrayText',
        borderRadius: '2rem',
      });
      expect(exports.result.input).toMatchObject({
        props: {
          style: { backgroundColor: 'pink', minHeight: '2.25rem', width: '100%' },
        },
        tag: 'input',
      });
      expect(exports.result.badge).toMatchObject({
        props: { style: { borderRadius: '9999px', display: 'inline-flex' } },
        tag: 'span',
      });
      expect(exports.result.dialog.props.style).toMatchObject({
        boxShadow: '0 1rem 2.5rem rgba(0, 0, 0, 0.2)',
        width: '18rem',
      });
      expect(exports.result.popover.props.style).toMatchObject({
        position: 'relative',
        width: 'min(20rem, calc(100% - 2rem))',
      });
      expect(exports.result.trigger).toMatchObject({
        props: { style: { justifyContent: 'space-between', width: '100%' } },
        tag: 'button',
      });
      expect(exports.result.spinner).toMatchObject({
        props: {
          style: {
            animation: 'var(--animate-spin, react-preview-generated-ui-spin 1s linear infinite)',
            borderRightColor: 'transparent',
            height: '1rem',
            width: '1rem',
          },
        },
        tag: 'div',
      });
      expect(exports.result.skeleton).toMatchObject({
        props: {
          style: {
            animation:
              'var(--animate-pulse, react-preview-generated-ui-pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite)',
            minHeight: '1rem',
          },
        },
        tag: 'div',
      });
      expect(exports.result.spinnerAuthored).toMatchObject({
        props: { style: { animation: 'none', borderRightColor: 'red' } },
        tag: 'div',
      });
      expect(injectedStyles).toHaveLength(1);
      expect(injectedStyles[0]).toMatchObject({
        id: 'react-preview-generated-ui-semantic-animations',
      });
      expect(injectedStyles[0]?.textContent).toContain(
        '@keyframes react-preview-generated-ui-spin',
      );
      expect(injectedStyles[0]?.textContent).toContain(
        '@keyframes react-preview-generated-ui-pulse',
      );
      expect(exports.result.slotted).toMatchObject({
        props: { style: { backgroundColor: 'ButtonFace', color: 'tomato' } },
        tag: 'a',
      });
      expect(result.warnings).toHaveLength(1);
    } finally {
      await rm(workspaceRoot, { force: true, recursive: true });
    }
  });

  /** Shares importer analysis and parent marker evidence, then refreshes both on rebuild. */
  it('shares one analysis and marker lookup across same-directory aliases', async () => {
    typescriptTraversal.sourceFileVisits.mockClear();
    const workspaceRoot = await mkdtemp(path.join(tmpdir(), 'react-preview-generated-cache-ui-'));
    const appRoot = path.join(workspaceRoot, 'app');
    const entryPath = path.join(appRoot, 'src', 'Page.tsx');
    const markerPath = path.join(appRoot, 'styles', 'README.md');
    const markerText =
      'This UI tree is autogenerated by the registry build process and gitignored.';
    let sourceText = [
      "import * as Buttons from '@/styles/ui/buttons';",
      "import * as Icons from '@/styles/ui/icons';",
      'export const result = [',
      "  Buttons.Button({ children: 'Button' }),",
      "  Icons.SearchIcon({ children: 'Search' }),",
      '];',
    ].join('\n');
    try {
      await Promise.all([
        mkdir(path.dirname(entryPath), { recursive: true }),
        mkdir(path.join(appRoot, 'styles'), { recursive: true }),
      ]);
      await Promise.all([
        writeAliasConfig(appRoot),
        writeFile(markerPath, markerText, 'utf8'),
        writeFile(entryPath, sourceText, 'utf8'),
      ]);
      const canonicalEntryPath = await realpath(entryPath);
      const resolver = createPreviewStaticModuleResolver({ workspaceRoot });
      const readSource = vi.fn((sourcePath: string) =>
        sourcePath === canonicalEntryPath ? sourceText : undefined,
      );
      const registerWatchDirectory = vi.fn(() => {
        // The second same-directory alias can resolve only from cached marker evidence.
        if (existsSync(markerPath)) unlinkSync(markerPath);
      });
      const incrementalBuild = await context({
        absWorkingDir: workspaceRoot,
        bundle: true,
        entryPoints: [entryPath],
        format: 'cjs',
        logLevel: 'silent',
        plugins: [
          createPreviewGeneratedUiFallbackPlugin({
            readSource,
            registerWatchDirectory,
            staticModuleResolver: resolver,
            workspaceRoot,
          }),
          createReactFixturePlugin(),
        ],
        write: false,
      });
      try {
        const firstResult = await incrementalBuild.rebuild();
        const firstExports = executeCommonJs(firstResult.outputFiles[0]?.text ?? '') as {
          readonly result: readonly [
            { readonly props: Record<string, unknown> },
            { readonly props: Record<string, unknown> },
          ];
        };

        expect(readSource).toHaveBeenCalledTimes(1);
        expect(typescriptTraversal.sourceFileVisits).toHaveBeenCalledOnce();
        expect(typescriptTraversal.sourceFileVisits).toHaveBeenLastCalledWith(canonicalEntryPath);
        expect(registerWatchDirectory).toHaveBeenCalledTimes(2);
        expect(existsSync(markerPath)).toBe(false);
        expect(firstExports.result[0].props['data-react-preview-generated-component']).toBe(
          'Button',
        );
        expect(firstExports.result[1].props['data-react-preview-generated-component']).toBe(
          'SearchIcon',
        );

        sourceText = [
          "import * as Buttons from '@/styles/ui/buttons';",
          "import * as Icons from '@/styles/ui/icons';",
          'export const result = [',
          "  Buttons.Link({ children: 'Link' }),",
          "  Icons.CloseIcon({ children: 'Close' }),",
          '];',
        ].join('\n');
        await Promise.all([
          writeFile(entryPath, sourceText, 'utf8'),
          writeFile(markerPath, markerText, 'utf8'),
        ]);
        const secondResult = await incrementalBuild.rebuild();
        const secondExports = executeCommonJs(secondResult.outputFiles[0]?.text ?? '') as {
          readonly result: readonly [
            { readonly props: Record<string, unknown> },
            { readonly props: Record<string, unknown> },
          ];
        };

        expect(readSource).toHaveBeenCalledTimes(2);
        expect(typescriptTraversal.sourceFileVisits).toHaveBeenCalledTimes(2);
        expect(typescriptTraversal.sourceFileVisits).toHaveBeenLastCalledWith(canonicalEntryPath);
        expect(registerWatchDirectory).toHaveBeenCalledTimes(4);
        expect(secondExports.result[0].props['data-react-preview-generated-component']).toBe(
          'Link',
        );
        expect(secondExports.result[1].props['data-react-preview-generated-component']).toBe(
          'CloseIcon',
        );
      } finally {
        await incrementalBuild.dispose();
      }
    } finally {
      await rm(workspaceRoot, { force: true, recursive: true });
    }
  });

  /** Propagates downstream named demand through an authored star barrel without a workspace scan. */
  it('exposes generated UI names re-exported through an authored star barrel', async () => {
    const workspaceRoot = await mkdtemp(path.join(tmpdir(), 'react-preview-generated-barrel-ui-'));
    const appRoot = path.join(workspaceRoot, 'app');
    const entryPath = path.join(appRoot, 'src', 'Page.tsx');
    const barrelPath = path.join(appRoot, 'src', 'barrel.ts');
    try {
      await Promise.all([
        mkdir(path.dirname(entryPath), { recursive: true }),
        mkdir(path.join(appRoot, 'styles'), { recursive: true }),
      ]);
      await Promise.all([
        writeAliasConfig(appRoot),
        writeFile(
          path.join(appRoot, 'styles', 'README.md'),
          'This UI tree is autogenerated by the registry build process and gitignored.',
          'utf8',
        ),
        writeFile(barrelPath, "export * from '@/styles/theme/ui/button';", 'utf8'),
        writeFile(
          entryPath,
          [
            "import { Button } from './barrel';",
            "export const result = Button({ children: 'From barrel' });",
          ].join('\n'),
          'utf8',
        ),
      ]);
      const resolver = createPreviewStaticModuleResolver({ workspaceRoot });
      const result = await buildFixture(entryPath, workspaceRoot, [
        createPreviewGeneratedUiFallbackPlugin({
          staticModuleResolver: resolver,
          workspaceRoot,
        }),
        createReactFixturePlugin(),
      ]);
      const exports = executeCommonJs(result.outputFiles?.[0]?.text ?? '') as {
        readonly result: { readonly props: Record<string, unknown>; readonly tag: string };
      };

      expect(exports.result).toMatchObject({
        children: ['From barrel'],
        props: { 'data-react-preview-generated-component': 'Button' },
        tag: 'button',
      });
      expect(result.warnings).toHaveLength(1);
    } finally {
      await rm(workspaceRoot, { force: true, recursive: true });
    }
  });

  /** Refuses an ordinary missing alias when no bounded marker explicitly proves generated output. */
  it('leaves unproven missing aliases as build errors', async () => {
    const workspaceRoot = await mkdtemp(path.join(tmpdir(), 'react-preview-unproven-ui-'));
    const appRoot = path.join(workspaceRoot, 'app');
    const entryPath = path.join(appRoot, 'src', 'Page.tsx');
    try {
      await Promise.all([
        mkdir(path.dirname(entryPath), { recursive: true }),
        mkdir(path.join(appRoot, 'styles'), { recursive: true }),
      ]);
      await Promise.all([
        writeAliasConfig(appRoot),
        writeFile(
          path.join(appRoot, 'styles', 'README.md'),
          'Hand-authored application styles live here.',
          'utf8',
        ),
        writeFile(
          entryPath,
          "import { Missing } from '@/styles/ui/missing'; export default Missing;",
          'utf8',
        ),
      ]);
      const resolver = createPreviewStaticModuleResolver({ workspaceRoot });

      await expect(
        buildFixture(entryPath, workspaceRoot, [
          createPreviewGeneratedUiFallbackPlugin({
            staticModuleResolver: resolver,
            workspaceRoot,
          }),
        ]),
      ).rejects.toThrow('Could not resolve "@/styles/ui/missing"');
    } finally {
      await rm(workspaceRoot, { force: true, recursive: true });
    }
  });

  /** Preserves normal authored source even when its parent directory documents generated siblings. */
  it('keeps existing aliased source on normal esbuild resolution', async () => {
    const workspaceRoot = await mkdtemp(path.join(tmpdir(), 'react-preview-existing-ui-'));
    const appRoot = path.join(workspaceRoot, 'app');
    const entryPath = path.join(appRoot, 'src', 'Page.ts');
    const componentPath = path.join(appRoot, 'styles', 'ui', 'button.ts');
    try {
      await Promise.all([
        mkdir(path.dirname(entryPath), { recursive: true }),
        mkdir(path.dirname(componentPath), { recursive: true }),
      ]);
      await Promise.all([
        writeAliasConfig(appRoot),
        writeFile(
          path.join(appRoot, 'styles', 'README.md'),
          'This tree is autogenerated by a documented build process.',
          'utf8',
        ),
        writeFile(componentPath, "export const Button = 'authored';", 'utf8'),
        writeFile(
          entryPath,
          "import { Button } from '@/styles/ui/button'; export const result = Button;",
          'utf8',
        ),
      ]);
      const resolver = createPreviewStaticModuleResolver({ workspaceRoot });
      const result = await buildFixture(entryPath, workspaceRoot, [
        createPreviewGeneratedUiFallbackPlugin({
          staticModuleResolver: resolver,
          workspaceRoot,
        }),
      ]);
      const exports = executeCommonJs(result.outputFiles?.[0]?.text ?? '');

      expect(exports.result).toBe('authored');
      expect(result.warnings).toHaveLength(0);
    } finally {
      await rm(workspaceRoot, { force: true, recursive: true });
    }
  });

  /** Rejects a lexical workspace alias whose nearest real ancestor is an external symlink. */
  it('does not read generated markers or watch paths outside the workspace through symlinks', async () => {
    const workspaceRoot = await mkdtemp(path.join(tmpdir(), 'react-preview-generated-link-'));
    const externalRoot = await mkdtemp(path.join(tmpdir(), 'react-preview-generated-external-'));
    const appRoot = path.join(workspaceRoot, 'app');
    const entryPath = path.join(appRoot, 'src', 'Page.tsx');
    try {
      await mkdir(path.dirname(entryPath), { recursive: true });
      await Promise.all([
        writeAliasConfig(appRoot),
        writeFile(
          path.join(externalRoot, 'README.md'),
          'This source is autogenerated by the build process and gitignored.',
          'utf8',
        ),
        writeFile(
          entryPath,
          "import { Button } from '@/styles/ui/button'; export default Button;",
          'utf8',
        ),
      ]);
      await symlink(externalRoot, path.join(appRoot, 'styles'));
      const resolver = createPreviewStaticModuleResolver({ workspaceRoot });
      const registerWatchDirectory = vi.fn();

      expect(
        resolver.resolveMissingPathAliasCandidate('@/styles/ui/button', entryPath),
      ).toBeUndefined();
      await expect(
        buildFixture(entryPath, workspaceRoot, [
          createPreviewGeneratedUiFallbackPlugin({
            registerWatchDirectory,
            staticModuleResolver: resolver,
            workspaceRoot,
          }),
        ]),
      ).rejects.toThrow('Could not resolve "@/styles/ui/button"');
      expect(registerWatchDirectory).not.toHaveBeenCalled();
    } finally {
      await Promise.all([
        rm(workspaceRoot, { force: true, recursive: true }),
        rm(externalRoot, { force: true, recursive: true }),
      ]);
    }
  });
});

/** Writes the nearest project config used by both esbuild and the preview's static resolver. */
async function writeAliasConfig(appRoot: string): Promise<void> {
  await writeFile(
    path.join(appRoot, 'tsconfig.json'),
    JSON.stringify({
      compilerOptions: { baseUrl: '.', jsx: 'react-jsx', paths: { '@/*': ['./*'] } },
    }),
    'utf8',
  );
}

/** Runs one file-backed browser bundle entirely in memory. */
async function buildFixture(
  entryPath: string,
  workspaceRoot: string,
  plugins: readonly Plugin[],
): Promise<Awaited<ReturnType<typeof build>>> {
  return await build({
    absWorkingDir: workspaceRoot,
    bundle: true,
    entryPoints: [entryPath],
    format: 'cjs',
    logLevel: 'silent',
    plugins: [...plugins],
    write: false,
  });
}

/** Supplies only the React element operations exercised by generated structural placeholders. */
function createReactFixturePlugin(): Plugin {
  return {
    name: 'react-fixture',
    setup(buildContext): void {
      buildContext.onResolve({ filter: /^react$/ }, () => ({
        namespace: 'react-fixture',
        path: 'react',
      }));
      buildContext.onLoad({ filter: /.*/, namespace: 'react-fixture' }, () => ({
        contents: [
          'const contextValues = new Map();',
          'const render = (element) => {',
          "  if (element === null || typeof element !== 'object' || !('tag' in element)) return element;",
          "  const providerContext = typeof element.tag === 'function' ? Object.getOwnPropertyDescriptor(element.tag, '__previewContext')?.value : undefined;",
          '  if (providerContext !== undefined) {',
          '    const hadValue = contextValues.has(providerContext);',
          '    const previous = contextValues.get(providerContext);',
          '    contextValues.set(providerContext, element.props?.value);',
          '    const rendered = element.children.map(render);',
          '    if (hadValue) contextValues.set(providerContext, previous);',
          '    else contextValues.delete(providerContext);',
          '    return rendered.length === 1 ? rendered[0] : rendered;',
          '  }',
          "  if (typeof element.tag === 'function') return render(element.tag({ ...(element.props || {}), children: element.children.length === 1 ? element.children[0] : element.children }));",
          '  return { ...element, children: element.children.map(render) };',
          '};',
          'module.exports = {',
          '  __render: render,',
          '  createContext: (defaultValue) => {',
          '    const context = { defaultValue };',
          '    context.Provider = function Provider() {};',
          '    context.Provider.__previewContext = context;',
          '    return context;',
          '  },',
          '  createElement: (tag, props, ...children) => ({ children, props, tag }),',
          '  cloneElement: (element, props) => ({ ...element, props: { ...element.props, ...props } }),',
          "  isValidElement: (value) => Boolean(value && typeof value === 'object' && 'tag' in value),",
          '  useContext: (context) => contextValues.has(context) ? contextValues.get(context) : context.defaultValue,',
          '};',
        ].join('\n'),
        loader: 'js',
      }));
    },
  };
}

/**
 * Evaluates a deterministic test bundle and returns its CommonJS exports.
 *
 * Optional globals model narrow browser capabilities, such as the style host used by animation
 * fallbacks, without giving generated-module tests an ambient Node or DOM dependency.
 */
function executeCommonJs(
  sourceText: string,
  globals: Readonly<Record<string, unknown>> = {},
): Record<string, unknown> {
  const module = { exports: {} as Record<string, unknown> };
  vm.runInNewContext(sourceText, { ...globals, exports: module.exports, module });
  return module.exports;
}
